project:
  type: website
  output-dir: docs

website:
  title: "Illuminate Data with R"
  back-to-top-navigation: true
  page-navigation: true
  navbar:
    background: dark
    search: false
    # logo: 
    right:
      - text: Meet People
        href: people.qmd
      - text: Presentations
        href: slides.qmd
      - text: Books
        href: books.qmd
      - text: Datasets
        href: data.qmd
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/lugoga/kitaa
      # - icon: twitter
      #   href: https://twitter.com
      # - icon: youtube
      #   href: https://www.youtube.com/user/Alfrodo123
      # You can ignore this part in the first step
      - icon: rss
        href: blog.xml
      - text: Ressources
        menu: 
          - text: Semba blog
            href: https://semba-blog.netlify.app/
          - text: Semba website
            href: https://lugoga.github.io/semba-quarto/
          - text: Nyamisi blog
            href: https://nyamisi.github.io/nyamisi/blog.html
          - text: R Weekly
            href: https://rweekly.org/
          - text: R Bloggers
            href: https://www.r-bloggers.com/
      - text: Archive
        href: archive.qmd
  google-analytics: <Insert your ID here>
  cookie-consent: true
  twitter-card: 
    image: thumbnail_blog.png
    card-style: summary_large_image
    creator: "@semba2024"
feed: true

# filters:
#   - code-filename
######################### 


format:
  html:
    theme: litera
    css: styles.css
    include-after-body: footer.html



