project:
  type: website
  output-dir: docs

website:
  title: "DATIKA"
  back-to-top-navigation: false
  page-navigation: true
  description: "Coding for all for better today and tommorow"
  
  navbar:
    background: dark
    search: false
    # logo: 
    right:
      - text: Posts
        href: blog.qmd
      - text: Presentations
        href: slides.qmd
      - text: Books
        href: books.qmd
      - text: Datasets
        href: data.qmd
      - text: Gallery
        href: photos.qmd
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/lugoga/kitaa
      # - icon: twitter
      #   href: https://twitter.com
      # - icon: youtube
      #   href: https://www.youtube.com/user/Alfrodo123
      # You can ignore this part in the first step
      - icon: rss
        href: blog.xml
      - text: Ressources
        menu: 
          - text: Semba blog
            href: https://semba-blog.netlify.app/
          - text: Semba website
            href: https://lugoga.github.io/semba-quarto/
          - text: Nyamisi blog
            href: https://nyamisi.github.io/nyamisi/blog.html
          - text: R Weekly
            href: https://rweekly.org/
          - text: R Bloggers
            href: https://www.r-bloggers.com/
      - text: Archive
        href: archive.qmd
  google-analytics: G-8KY4TDP558
  cookie-consent: true
  twitter-card: 
    image: thumbnail_blog.png
    card-style: summary_large_image
    creator: "@semba2024"
    
  page-footer:
    left:  "&copy;2024 [Datika](index.qmd)"
    center:
      - text: "FAQ"
        href: faq.qmd
      - text: "Feedback"
        href: feedback.qmd
      - text: "License"
        href: license.qmd
      - text: "Terms"
        href: terms.qmd
        
feed: true


# csl: apa.csl



# filters:
#   - code-filename
######################### 


# format:
#   html:
#     theme: litera
#     css: styles.css
#     include-after-body: footer.html

# borrowed from other sources
format:
  html:
    code-fold: false
    code-tools: false
    code-line-numbers: true
    theme:
      - styles.scss
      # - theme-light.scss
      # - theme-dark.scss
    mainfont: Nunito
    toc: true
    toc-depth: 3



