{
  "hash": "152ae5fd6ad205a236b0330cf692a26e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Visualize the Peril of Global Ocean Aragonite Saturation with ggplot2\"\ndescription: \"This blog post provides an overview of the peril of global ocean aragonite saturation using ggplot2 for data visualization in R\"\nauthor: \n  - name: Masumbuko Semba\n    url: https://semba.netlify.app\n    orcid: 0000-0002-5002-9747\n    affiliation: Nelson Mandela African Institution of Science and Technology\n    affiliation-url: https://semba.netlify.app/  \ncitation: \n    url: https://lugoga.github.io/kitaa/posts/visualize_line2/\nbibliography: ../blog.bib\ncsl:  ../elsevier.csl\ndate: \"2024-06-15\"\ntoc: true\ntoc-depth: 4\ncategories: [Data Science, Data Visualization, ggplot]\nimage: aragonite.png\ncode-fold: true\nexecute: \n  warning: false\n  message: false\n  comment: \"\"\n  \nfilters: \n  - webr\n\n---\n\n\n\n\n<!-- Google tag (gtag.js) -->\n<script async src=\"https://www.googletagmanager.com/gtag/js?id=G-8KY4TDP558\"></script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag('js', new Date());\n\n  gtag('config', 'G-8KY4TDP558');\n</script>\n\n\n\n\n## Introduction\n\n\nThe health of our oceans is under threat from human-induced climate change, particularly affecting the delicate balance of chemical processes that sustain marine life. One critical factor is the saturation of aragonite, a form of calcium carbonate essential for the formation of coral reefs and the shells of many marine organisms. As levels of atmospheric CO2 rise, so do the concentrations of dissolved CO2 in seawater, leading to a phenomenon known as ocean acidification. This blog post explores the peril of global ocean aragonite saturation using data visualization techniques in R, specifically with ggplot2.\n\nI have created a step-by-step guide to assist in creating an equal area map of aragonite using R. The provided code can also be utilized to map other spatial information in the same raster format. The Robinson projection, which is adopted in this guide, offers a balanced solution for representing the entire globe as a two-dimensional image. This approach can be particularly useful for visualizing global spatial data in a way that accurately represents the proportional areas of different regions.\n\n\n## Packages \n\nTo begin, we need to load the necessary packages and set a global theme for our visualizations. Here is a list of the required packages for data manipulation, spatial data handling, and plotting:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrequire(tidyverse)\nrequire(sf)\nrequire(terra)\nrequire(tidyterra)\n\ntheme_set(theme_minimal(base_size = 15)) # global theme\n```\n:::\n\n\n\n\n\n## Data\n\nFor this post, we'll use data from a NetCDF file containing projections of aragonite saturation levels in the global ocean. The data can be accessed either through [OA](https://www.ncei.noaa.gov/access/ocean-carbon-acidification-data-system/synthesis/surface-oa-indicators.html) or \n[OA data](https://www.ncei.noaa.gov/data/oceans/ncei/ocads/data/0259391/nc/median/). The data spans from 2020 to 2100 and covers the entire globe. To explore the contents and structure of the NetCDF file Aragonite_median_ssp370.nc, we can use the tidync package in R. This package provides tools for efficiently working with NetCDF data. The following code snippet will load the dataset and display its information:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidync::tidync(\"../data/Aragonite_median_ssp370.nc\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nData Source (1): Aragonite_median_ssp370.nc ...\n\nGrids (3) <dimension family> : <associated variables> \n\n[1]   D0,D1,D2 : aragonite    **ACTIVE GRID** ( 583200  values per variable)\n[2]   D0,D1    : longitude, latitude\n[3]   D2       : time\n\nDimensions 3 (all active): \n  \n  dim   name  length   min   max start count  dmin  dmax unlim coord_dim \n  <chr> <chr>  <dbl> <dbl> <dbl> <int> <int> <dbl> <dbl> <lgl> <lgl>     \n1 D0    lon      360     1   360     1   360     1   360 FALSE FALSE     \n2 D1    lat      180     1   180     1   180     1   180 FALSE FALSE     \n3 D2    time       9  2020  2100     1     9  2020  2100 FALSE TRUE      \n```\n\n\n:::\n:::\n\n\nThe `tidync` function from the **tidync** package reads the NetCDF file and provides a tidy representation of its contents. This includes information about the variables, dimensions, and metadata contained in the file\n\nThe Aragonite_median_ssp370.nc NetCDF file contains three dimensions: longitude (lon), latitude (lat), and time (time). The lon dimension has 360 values representing longitudinal coordinates, the lat dimension has 180 values representing latitudinal coordinates, and the time dimension has 9 values representing the years from 2020 to 2100.\n\n\nThe .nc file format stands for NetCDF (Network Common Data Form), a widely used format for storing multi-dimensional scientific data such as climate and oceanographic variables. NetCDF files are efficient for handling large datasets, allowing easy access and manipulation of subsets of data. Next, we load the dataset Aragonite_median_ssp370.nc, which contains data on aragonite saturation. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nar = rast(\"../data/Aragonite_median_ssp370.nc\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"vobjtovarid4: **** WARNING **** I was asked to get a varid for dimension named lon BUT this dimension HAS NO DIMVAR! Code will probably fail at this point\"\n[1] \"vobjtovarid4: **** WARNING **** I was asked to get a varid for dimension named lat BUT this dimension HAS NO DIMVAR! Code will probably fail at this point\"\n```\n\n\n:::\n\n```{.r .cell-code}\nar\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass       : SpatRaster \ndimensions  : 180, 360, 9  (nrow, ncol, nlyr)\nresolution  : 1, 1  (x, y)\nextent      : 0.5, 360.5, 0.5, 180.5  (xmin, xmax, ymin, ymax)\ncoord. ref. :  \nsource      : Aragonite_median_ssp370.nc:aragonite \nvarname     : aragonite \nnames       : aragonite_1, aragonite_2, aragonite_3, aragonite_4, aragonite_5, aragonite_6, ... \nunit        :         N/A,         N/A,         N/A,         N/A,         N/A,         N/A, ... \n```\n\n\n:::\n:::\n\n\nThen plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nar[[1]] |> plot()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\nwe notice that the longitude are in 360 degree hence we use the `rotate` function from the terra package. This function adjusts the data to ensure the longitude coordinates are correctly handled from 0-360 to -180 and 180 extents\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nar2 = ar |> rotate()\nar2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass       : SpatRaster \ndimensions  : 180, 360, 9  (nrow, ncol, nlyr)\nresolution  : 1, 1  (x, y)\nextent      : -179.5, 180.5, 0.5, 180.5  (xmin, xmax, ymin, ymax)\ncoord. ref. :  \nsource(s)   : memory\nvarname     : aragonite \nnames       : aragonite_1, aragonite_2, aragonite_3, aragonite_4, aragonite_5, aragonite_6, ... \nmin values  :        0.44,        0.38,        0.26,        0.31,        0.30,        0.30, ... \nmax values  :        4.50,        4.36,        4.20,        4.07,        3.87,        3.73, ... \nunit        :         N/A,         N/A,         N/A,         N/A,         N/A,         N/A, ... \n```\n\n\n:::\n:::\n\nThe ar2 SpatRaster object lack coordinate reference system (CRS). The CRS defines how the spatial data's coordinates (latitude and longitude) relate to locations on the Earth's surface. Without this information, it is unclear what geographic or projection system the coordinates refer to, which can lead to misinterpretation of the data's spatial context and hinder accurate spatial analysis or integration with other geospatial datasets. Adding an appropriate CRS would ensure that the data is correctly georeferenced and interpretable in a global or regional spatial context.\n\n\n\nTo fix the missing CRS in the SpatRaster object, use the terra package's `crs` function to assign the appropriate CRS to the dataset. The WGS 84 (World Geodetic System 1984) coordinate system is the most widely used geodetic system, and it is also known as EPSG:4326. This system uses a geographic coordinate system with coordinates defined by latitude and longitude on the Earth's surface.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrs(ar2) = \"epsg:4326\"\nar2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass       : SpatRaster \ndimensions  : 180, 360, 9  (nrow, ncol, nlyr)\nresolution  : 1, 1  (x, y)\nextent      : -179.5, 180.5, 0.5, 180.5  (xmin, xmax, ymin, ymax)\ncoord. ref. : lon/lat WGS 84 (EPSG:4326) \nsource(s)   : memory\nvarname     : aragonite \nnames       : aragonite_1, aragonite_2, aragonite_3, aragonite_4, aragonite_5, aragonite_6, ... \nmin values  :        0.44,        0.38,        0.26,        0.31,        0.30,        0.30, ... \nmax values  :        4.50,        4.36,        4.20,        4.07,        3.87,        3.73, ... \nunit        :         N/A,         N/A,         N/A,         N/A,         N/A,         N/A, ... \n```\n\n\n:::\n:::\n\nWe also notice that latitude is arranged from 0.5 to 180.05 instead of -90 and 90 degree. To set the extent of the SpatRaster object `ar2` to cover the entire globe from -180° to 180° longitude and -90° to 90° latitude, you can use the `ext` function from the **terra** package. This function allows you to specify the spatial extent of the raster.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\next(ar2) = ext(-180, 180, -90, 90)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nar2[[1]] |> plot()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nThe metadata of the file contain informationof the timeline, which contain data from 2020 to 2100 at the interva of ten years. Therefore, we need to replace the aragonite names to years, which are descriptive and easy to understand. To assign names to the layers of a SpatRaster object ar2 with the years 2020 to 2100, you can use the names function in R. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(ar2) = seq(2020,2100, length.out = nlyr(ar2))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(ar2, las = 1)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n## Visualizing Global Aragonite Saturation\n\nTo visualize global aragonite saturation levels, we'll create a tile plot using ggplot2. This will provide a comprehensive view of how aragonite saturation varies across the globe. To visualize aragonite saturation levels with raster data, contours, and contour text, and facet it by each layer (year), you can follow this approach. Ensure you have the necessary packages loaded  (terra, tidyterra and ggplot2).\n\n1. First, we can use the raster data from the SpatRaster object ar2 to create a plot with contours and contour text using ggplot2. This can be achieved by `geom_spatraster` and `geom_spatraster_contour_text` function from **tidyterra** package to plot the raster data, add contour lines, and label the contours with text.\n\n2. Since our SpatRaster object contains multiple layers representing different years, we can use the `facet_wrap()` function in **ggplot2** to create a separate panel for each layer (year) of the SpatRaster object. This allows us to compare the Aragonite saturation across different years in a single visualization.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_spatraster(data = ar2) +\n  geom_spatraster_contour_text(data = ar2, breaks = c(1.5,2.5), size = 3) +\n  scale_fill_gradientn(colours = hcl.colors(n = 12, palette = \"RdBu\", rev = F),trans = scales::sqrt_trans(), na.value = \"black\")+\n  facet_wrap(~lyr, nrow = 4)+\n  theme_void()\n```\n\n::: {.cell-output-display}\n![The flat world map of aragonite saturation over the years](index_files/figure-html/fig-flat-1.png){#fig-flat width=672}\n:::\n:::\n\nThis plot gives us an initial impression of the spatial distribution of aragonite saturation levels across the globe. However, we can improve the visualization using the Robinson projection. The Robinson projection is well-suited for making world maps because it effectively minimizes size and shape distortions of continents. You can apply this projection string in functions that accept Proj.4 strings, such as those found in the sf or rgdal packages in R.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrobin = \"+proj=robin +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs\"\n```\n:::\n\n\n\nDefine a color ramp for the oxygen gradient and plot the map.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmycolors <- c(\"#6FBBE8\",\"#A1ECD8\",\"#F6F9AB\",\"#FCB46D\",\"#B21414\",\"#D278E4\",\"#9914B3\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() + \n  geom_spatraster(data = ar2)+\n  # geom_sf(data=world.sf) +\n  coord_sf(crs = robin)+\n  # scale_fill_gradientn(colours = mycolors, trans = scales::sqrt_trans(), na.value = NA)+\n    scale_fill_gradientn(colours = hcl.colors(n = 12, palette = \"RdBu\", rev = F),trans = scales::sqrt_trans(), na.value = NA)+\n  cowplot::theme_minimal_grid()+\n  facet_wrap(~lyr, nrow = 3)\n```\n\n::: {.cell-output-display}\n![The flat world map of aragonite saturation over the years](index_files/figure-html/fig-robin-1.png){#fig-robin width=672}\n:::\n:::\n\n\nThe Final map\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() + \n  geom_spatraster(data = ar2)+\n  coord_sf(crs= robin)+\n  scale_fill_gradientn(\n    name = \"Aragonite\\nsaturation\", breaks = seq(0,4,.4),colours = mycolors, \n    trans = scales::sqrt_trans(), na.value = NA)+\n  cowplot::theme_minimal_hgrid(font_size = 10)+\n  facet_wrap(~lyr, nrow = 3)+\n  # titles\n  labs(\n    title = \"Coral Peril: Shrinking of Aragonite in Our Ocean\", \n    subtitle = str_wrap(\"By 2100, aragonite saturation states are projected to decline significantly due to increasing ocean acidification driven by rising atmospheric carbondioxide concentrations.\", width = 100),\n    caption = \"Each map represents projected aragonite saturation\",\n    x = NULL)  +\n  theme(\n    strip.background = element_blank(),\n    legend.key.height = unit(1.2,\"cm\"),\n    axis.line.y = element_blank(),\n    axis.line.x = element_blank(),\n    axis.text.x = element_blank(),\n    axis.ticks.x = element_blank(),\n    axis.title.y = element_blank(),\n    axis.ticks.length.y = unit(5, \"pt\"),\n    axis.ticks.y = element_line(linetype = \"solid\", linewidth = .15),\n    plot.subtitle = element_text(size = 10, face = \"plain\"),\n    plot.title = element_text(size = 18, family = \"fat\"),\n    plot.caption = element_text(hjust = 0, size = 8, color = \"grey50\"),\n    # plot.background = element_rect(fill = \"#d8cfd0\"),\n    # panel.background = element_rect(fill = \"#f2f1ef\")\n  ) \n```\n\n::: {.cell-output-display}\n![The flat world map of aragonite saturation over the years](index_files/figure-html/fig-robin2-1.png){#fig-robin2 width=672}\n:::\n:::\n\n\n## Conclusion\n\nIn summary, the visualization brings attention to the different aragonite saturation levels in the world's oceans and the possible consequences of ocean acidification on marine ecosystems. As aragonite saturation levels decline, it becomes increasingly challenging for marine organisms to build shells and skeletons, posing a threat to the diversity and ability to recover of coral reefs and other susceptible marine species.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwio = ext(40,120,-45,10)\n\nwio.vec = wio |> as.polygons() |> st_as_sf() |> st_set_crs(value = 4326)\n\n\nabc = ar2 |> \n  extract(wio.vec, )\n\nabc |> \n  sample_n(300) |> \n  pivot_longer(-ID, values_to = \"data\", names_to = \"year\") |> \n  ggplot(aes(x = year, y = data ))+\n  annotate(geom = \"rect\", xmin = c(\"2019\", \"2050\"), xmax = c(\"2050\", \"2101\"), ymin = 1, ymax = Inf, fill = c(\"firebrick4\", \"cyan4\"), alpha = .2)+\n  geom_boxplot(fill = \"steelblue\")+\n  scale_y_continuous(breaks = seq(.75,4,.5), name = \"Aragonite Saturation\")+\n  # titles\n  labs(\n    title = \"Coral Peril: Shrinking of Aragonite in Our Ocean\", \n    subtitle = str_wrap(\"By 2100, aragonite saturation states are projected to decline significantly due to increasing ocean acidification driven by rising carbondioxide concentrations.\", width = 85),\n    caption = \"Each boxplot represents projected aragonite saturation\",\n    x = NULL)  +\n  theme(\n    axis.ticks.length.y = unit(5, \"pt\"),\n    axis.ticks.y = element_line(linetype = \"solid\", linewidth = .15),\n    plot.subtitle = element_text(size = 10, face = \"plain\", color = \"steelblue4\"),\n    plot.title = element_text(size = 17, family = \"fat\"),\n    plot.caption = element_text(hjust = 0, size = 8, color = \"grey50\"),\n    # plot.background = element_rect(fill = \"#d8cfd0\"),\n    # panel.background = element_rect(fill = \"#f2f1ef\")\n  ) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-1.png){width=576}\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n\n## References\n\n\n\n\n\n\n\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}