{
  "hash": "9796a6678d470a78287997ba0002e840",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Data cleaning, merging, and appending\"\nauthor: \n  - name: Masumbuko Semba\n    url: https://semba.netlify.app\n    orcid: 0000-0002-5002-9747\n    affiliation: Nelson Mandela African Institution of Science and Technology\n    affiliation-url: https://semba.netlify.app/  \ncitation: \n    url: https://lugoga.github.io/kitaa/posts/manipulate/\nbibliography: ../blog.bib\ncsl:  ../elsevier.csl\ndate: \"2024-05-01\"\ncategories: [visualization, code, analysis]\nimage: https://media.istockphoto.com/id/1448152453/vector/big-data-technology-and-data-science-illustration-data-flow-concept-querying-analysing.jpg?s=612x612&w=0&k=20&c=To0lhCrVmDYdSkOUOGxGsjlYe0buj_wwGCDqYhF9p2o=\nexecute: \n  warning: false\n  message: false\n  comment: \"\"\nnumber-sections: true  \n---\n\n::: {.cell}\n\n:::\n\n\n\n\n## Introduction\n\nIn reality, data `cleaning` is not so much its own step in the data wrangling process as it is a constant activity that accompanies every other step, both because most data is not clean when we encounter it, and because how a data set (or part of it) needs to be “cleaned” is often revealed progressively as we work. At a high level, clean data might be summarized as being free from errors or typos -- such as mismatched units, multiple spellings of the same word or term, and fields that are not well-separated -- and missing or impossible values.\n\nWhile many of these are at least somewhat straightforward to recognize (though not always to correct), however, deeper data problems may still persist. Measurement changes, calculation errors and other oversights -- especially in system-generated data -- often don’t reveal themselves until some level of analysis has been done and the data has been “reality-checked” with folks who significant expertise and/or first-hand experience with the subject.\n\n\n\n```{mermaid}\nflowchart LR\n  A[Main variable types] --> B{Catrgorical}\n  A[Main variable types] --> C{Numeric}\n  B{Catrgorical} --> D[ordinal]\n  B{Catrgorical} --> E[non-ordinal]\n  C{Numeric} --> F[continuous]\n  C{Numeric} --> G[discrete]\n```\n\n\n\nThe iterative nature of data cleaning is an example of why data wrangling is a cycle rather than a linear series of steps: as your work reveals more about the data and your understanding of its relationship to the world deepens, you may find that you need to revisit earlier work that you’ve done and repeat or adjust certain aspects of the data\n\n\n\n### Importing data\n\nAlthough creating data frames from existing data structures is extremely useful, by far the most common approach is to create a data frame by importing data from an external file. To do this, you’ll need to have your data correctly formatted and saved in a file format that R is able to recognize. Fortunately for us, R is able to recognize a wide variety of file formats, although in reality you’ll probably end up only using two or three regularly---comma separated, excel spreadsheet and tab-delimited.\n\nThe easiest method of creating a data file to import into R is to enter your data into a spreadsheet using either Microsoft Excel or LibreOffice Calc and save the spreadsheet as a comma separated (`.csv`), excel spreadsheet (`.xls` or `.xlsx`) and tab-delimited (`.txt`). We then read the file into our session, for this mode, we are going to use the `LFQ_sample_1.xls`, which is an Excel spreadsheet file. To load into the R session, we use a `read_excel` function from **readxl** package [@readxl]. Before we import the data, we need to load the packages that we will use their functions in this chapter\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrequire(tidyverse)\nrequire(magrittr)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlfq = readxl::read_excel(path = \"../data/LFQ_sample_1.xls\",\n                         sheet = 1, \n                         skip = 0)\n```\n:::\n\n\n\n\nThere are a few things to note about the above command. First, the file path and the filename (including the file extension) needs to be enclosed in either single or double quotes (i.e. the data/flower.txt bit) as the `read_excel()` function expects this to be a character string. If your working directory is already set to the directory which contains the file, you don’t need to include the entire file path just the `filename`. \n\n\nIn the example above, the file path is separated with a single forward slash /. This will work regardless of the operating system you are using. The argument `sheet = 1` specify the function to pick the data from first sheet as spreadsheet store data in multiple sheet. The argument `skip = 0` specify the function not to skip any row in the datase. This used to specify when the data has metadata information at the top. \n\nAfter importing our data into R it doesn’t appear that R has done much, at least nothing appears in the R Console! To see the contents of the data frame we need to tell R to do so using a print `function`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlfq %>% print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 779 × 6\n   Date                Species `Size (cm)` `Size Class` `Gear type` Landing_site\n   <dttm>              <chr>         <dbl>        <dbl> <chr>       <chr>       \n 1 2019-05-30 00:00:00 Siganu…        16.5           18 Speargun    Pwani       \n 2 2019-05-30 00:00:00 Siganu…        12             12 Speargun    Pwani       \n 3 2019-05-30 00:00:00 Siganu…        15             15 Speargun    Pwani       \n 4 2019-05-30 00:00:00 Siganu…        33             33 Speargun    Pwani       \n 5 2019-05-30 00:00:00 Siganu…        11.2           12 hook and l… Pwani       \n 6 2019-05-30 00:00:00 Siganu…        17             18 hook and l… Pwani       \n 7 2019-05-30 00:00:00 Siganu…        19             21 Gill net    Pwani       \n 8 2019-05-30 00:00:00 Lethri…        10             12 Traps       Pwani       \n 9 2019-05-30 00:00:00 Lethri…        11             12 Traps       Pwani       \n10 2019-05-30 00:00:00 Lethri…         9             12 Traps       Pwani       \n# ℹ 769 more rows\n```\n\n\n:::\n:::\n\n\nThe data frame appears in the console and that prove to us that we successfully imported the data into R. But printing the imported data into console is only useful for small dataset and for large dataset that makes the console messy and there is nothing you can glean by simply printing the dataset in the console. The other common practice often used is looking on the internal structure of the dataset using `str()` function\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlfq %>% \n  str()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [779 × 6] (S3: tbl_df/tbl/data.frame)\n $ Date        : POSIXct[1:779], format: \"2019-05-30\" \"2019-05-30\" ...\n $ Species     : chr [1:779] \"Siganus sutor\" \"Siganus sutor\" \"Siganus sutor\" \"Siganus sutor\" ...\n $ Size (cm)   : num [1:779] 16.5 12 15 33 11.2 17 19 10 11 9 ...\n $ Size Class  : num [1:779] 18 12 15 33 12 18 21 12 12 12 ...\n $ Gear type   : chr [1:779] \"Speargun\" \"Speargun\" \"Speargun\" \"Speargun\" ...\n $ Landing_site: chr [1:779] \"Pwani\" \"Pwani\" \"Pwani\" \"Pwani\" ...\n```\n\n\n:::\n:::\n\n\nand a better solution is to use a tidyverse approach of `glimpse` function\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlfq %>% \n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 779\nColumns: 6\n$ Date         <dttm> 2019-05-30, 2019-05-30, 2019-05-30, 2019-05-30, 2019-05-…\n$ Species      <chr> \"Siganus sutor\", \"Siganus sutor\", \"Siganus sutor\", \"Sigan…\n$ `Size (cm)`  <dbl> 16.5, 12.0, 15.0, 33.0, 11.2, 17.0, 19.0, 10.0, 11.0, 9.0…\n$ `Size Class` <dbl> 18, 12, 15, 33, 12, 18, 21, 12, 12, 12, 12, 12, 12, 12, 1…\n$ `Gear type`  <chr> \"Speargun\", \"Speargun\", \"Speargun\", \"Speargun\", \"hook and…\n$ Landing_site <chr> \"Pwani\", \"Pwani\", \"Pwani\", \"Pwani\", \"Pwani\", \"Pwani\", \"Pw…\n```\n\n\n:::\n:::\n\n\nThe output in the console tell us that `lfq` dataset we just imported has six columns (variables) and 779 rows (records). Each of the variable are listed along with their data types and few records of the data\nThe first row of the data contains the variable (column) names. \n\n### Common import frustrations\n\nIt’s quite common to get a bunch of really frustrating error messages when you first start importing data into R. Perhaps the most common is\n\n\n```r\nlfq = readxl::read_excel(path = \"assets/fao_paul_dataset/LFQ_sample_1\",\n                         sheet = 1, \n                         skip = 0)\n\n```\n\nThis error message is telling you that R cannot find the file you are trying to import. Several reasons can lead to that information error.The first is that you’ve made a mistake in the spelling of either the filename or file path. Another common mistake is that you have forgotten to include the file extension in the filename (i.e. .txt). Lastly, the file is not where you say it is or you’ve used an incorrect file path. Using RStudio Projects and having a logical directory structure goes a long way to avoiding these types of errors.\n\n\n\n### clean variable names\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlfq %>% \n  names()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Date\"         \"Species\"      \"Size (cm)\"    \"Size Class\"   \"Gear type\"   \n[6] \"Landing_site\"\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlfq.clean = lfq %>% \n  janitor::clean_names() %>% \n  janitor::remove_empty()\n```\n:::\n\n\n### check the structure\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlfq.clean %>% \n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 779\nColumns: 6\n$ date         <dttm> 2019-05-30, 2019-05-30, 2019-05-30, 2019-05-30, 2019-05-…\n$ species      <chr> \"Siganus sutor\", \"Siganus sutor\", \"Siganus sutor\", \"Sigan…\n$ size_cm      <dbl> 16.5, 12.0, 15.0, 33.0, 11.2, 17.0, 19.0, 10.0, 11.0, 9.0…\n$ size_class   <dbl> 18, 12, 15, 33, 12, 18, 21, 12, 12, 12, 12, 12, 12, 12, 1…\n$ gear_type    <chr> \"Speargun\", \"Speargun\", \"Speargun\", \"Speargun\", \"hook and…\n$ landing_site <chr> \"Pwani\", \"Pwani\", \"Pwani\", \"Pwani\", \"Pwani\", \"Pwani\", \"Pw…\n```\n\n\n:::\n:::\n\n\n### creating variables\n\nYou notice that the date is datetime and date but the display is date. Thus, we need to create three variables that represent `day`, `month`, and `year`. We can extract these variables from date variables, We can use the `day()`, `month()`, and `year()` functions from **lubridate** package [@lubridate];\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlfq.time = lfq.clean %>% \n  mutate(\n    day = lubridate::day(date),\n    month = lubridate::month(date),\n    year = lubridate::year(date)\n    ) %>% \n  relocate(c(landing_site, day, month, year), .before = date)\n\nlfq.time |> \n  sample_n(30) |> \n  select(-c(day, month, year)) |> \n  flextable::flextable() |> \n  flextable::autofit()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-1d73f0d8{}.cl-1d6a96f0{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-1d6dd630{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-1d6dd63a{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-1d6de792{width:1.101in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de79c{width:1.704in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de79d{width:1.831in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de79e{width:0.845in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7a6{width:0.99in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7a7{width:1.194in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7a8{width:1.101in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7a9{width:1.704in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7b0{width:1.831in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7b1{width:0.845in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7b2{width:0.99in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7b3{width:1.194in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7ba{width:1.101in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7bb{width:1.704in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7bc{width:1.831in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7bd{width:0.845in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7be{width:0.99in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7c4{width:1.194in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7c5{width:1.101in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7c6{width:1.704in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7ce{width:1.831in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7cf{width:0.845in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7d0{width:0.99in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7d1{width:1.194in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7d8{width:1.101in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7d9{width:1.704in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7da{width:1.831in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7e2{width:0.845in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7e3{width:0.99in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7e4{width:1.194in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7ec{width:1.101in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7ed{width:1.704in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7ee{width:1.831in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7ef{width:0.845in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7f6{width:0.99in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1d6de7f7{width:1.194in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-1d73f0d8'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-1d6de792\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">landing_site</span></p></th><th class=\"cl-1d6de79c\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">date</span></p></th><th class=\"cl-1d6de79d\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">species</span></p></th><th class=\"cl-1d6de79e\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">size_cm</span></p></th><th class=\"cl-1d6de7a6\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">size_class</span></p></th><th class=\"cl-1d6de7a7\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">gear_type</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7a8\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Pwani</span></p></td><td class=\"cl-1d6de7a9\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2019-07-12 00:00:00</span></p></td><td class=\"cl-1d6de7b0\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Anampses spp.</span></p></td><td class=\"cl-1d6de7b1\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">14.0</span></p></td><td class=\"cl-1d6de7b2\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">15</span></p></td><td class=\"cl-1d6de7b3\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Gill net</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7ba\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Bahari</span></p></td><td class=\"cl-1d6de7bb\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2020-04-08 00:00:00</span></p></td><td class=\"cl-1d6de7bc\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Leptoscarus vaigiensis</span></p></td><td class=\"cl-1d6de7bd\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">19.8</span></p></td><td class=\"cl-1d6de7be\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">21</span></p></td><td class=\"cl-1d6de7c4\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Speargun</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7ba\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Pwani</span></p></td><td class=\"cl-1d6de7bb\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2019-07-11 00:00:00</span></p></td><td class=\"cl-1d6de7bc\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Leptoscarus vaigiensis</span></p></td><td class=\"cl-1d6de7bd\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">25.5</span></p></td><td class=\"cl-1d6de7be\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">27</span></p></td><td class=\"cl-1d6de7c4\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Speargun</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7ba\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Pwani</span></p></td><td class=\"cl-1d6de7bb\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2019-07-11 00:00:00</span></p></td><td class=\"cl-1d6de7bc\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Lutjanus fulviflamma</span></p></td><td class=\"cl-1d6de7bd\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">27.5</span></p></td><td class=\"cl-1d6de7be\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">30</span></p></td><td class=\"cl-1d6de7c4\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">hook and line</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7ba\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Bahari</span></p></td><td class=\"cl-1d6de7bb\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2020-07-25 00:00:00</span></p></td><td class=\"cl-1d6de7bc\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Siganus sutor</span></p></td><td class=\"cl-1d6de7bd\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">13.8</span></p></td><td class=\"cl-1d6de7be\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">15</span></p></td><td class=\"cl-1d6de7c4\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Traps</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7ba\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Pwani</span></p></td><td class=\"cl-1d6de7bb\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2019-07-11 00:00:00</span></p></td><td class=\"cl-1d6de7bc\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Calotomus carolinus</span></p></td><td class=\"cl-1d6de7bd\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">16.0</span></p></td><td class=\"cl-1d6de7be\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">18</span></p></td><td class=\"cl-1d6de7c4\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Speargun</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7ba\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Pwani</span></p></td><td class=\"cl-1d6de7bb\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2019-05-30 00:00:00</span></p></td><td class=\"cl-1d6de7bc\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Leptoscarus vaigiensis</span></p></td><td class=\"cl-1d6de7bd\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">15.6</span></p></td><td class=\"cl-1d6de7be\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">18</span></p></td><td class=\"cl-1d6de7c4\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Speargun</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7ba\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Pwani</span></p></td><td class=\"cl-1d6de7bb\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2019-07-12 00:00:00</span></p></td><td class=\"cl-1d6de7bc\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Siganus sutor</span></p></td><td class=\"cl-1d6de7bd\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">17.5</span></p></td><td class=\"cl-1d6de7be\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">18</span></p></td><td class=\"cl-1d6de7c4\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Traps</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7ba\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Pwani</span></p></td><td class=\"cl-1d6de7bb\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2019-06-25 00:00:00</span></p></td><td class=\"cl-1d6de7bc\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Siganus sutor</span></p></td><td class=\"cl-1d6de7bd\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">18.4</span></p></td><td class=\"cl-1d6de7be\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">21</span></p></td><td class=\"cl-1d6de7c4\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Traps</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7c5\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Pwani</span></p></td><td class=\"cl-1d6de7c6\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2019-07-11 00:00:00</span></p></td><td class=\"cl-1d6de7ce\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Calotomus carolinus</span></p></td><td class=\"cl-1d6de7cf\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">15.5</span></p></td><td class=\"cl-1d6de7d0\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">18</span></p></td><td class=\"cl-1d6de7d1\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Beach seine</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7d8\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Pwani</span></p></td><td class=\"cl-1d6de7d9\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2019-05-30 00:00:00</span></p></td><td class=\"cl-1d6de7da\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Lethrinus mahsena</span></p></td><td class=\"cl-1d6de7e2\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">11.1</span></p></td><td class=\"cl-1d6de7e3\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">12</span></p></td><td class=\"cl-1d6de7e4\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">hook and line</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7ba\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Pwani</span></p></td><td class=\"cl-1d6de7bb\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2019-07-12 00:00:00</span></p></td><td class=\"cl-1d6de7bc\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Siganus sutor</span></p></td><td class=\"cl-1d6de7bd\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">27.5</span></p></td><td class=\"cl-1d6de7be\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">30</span></p></td><td class=\"cl-1d6de7c4\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Gill net</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7ba\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Bahari</span></p></td><td class=\"cl-1d6de7bb\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2020-07-25 00:00:00</span></p></td><td class=\"cl-1d6de7bc\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Siganus sutor</span></p></td><td class=\"cl-1d6de7bd\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">15.5</span></p></td><td class=\"cl-1d6de7be\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">18</span></p></td><td class=\"cl-1d6de7c4\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Traps</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7c5\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Pwani</span></p></td><td class=\"cl-1d6de7c6\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2019-07-11 00:00:00</span></p></td><td class=\"cl-1d6de7ce\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Calotomus carolinus</span></p></td><td class=\"cl-1d6de7cf\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">16.0</span></p></td><td class=\"cl-1d6de7d0\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">18</span></p></td><td class=\"cl-1d6de7d1\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Beach seine</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7ba\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Bahari</span></p></td><td class=\"cl-1d6de7bb\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2020-07-25 00:00:00</span></p></td><td class=\"cl-1d6de7bc\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Siganus sutor</span></p></td><td class=\"cl-1d6de7bd\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">16.0</span></p></td><td class=\"cl-1d6de7be\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">18</span></p></td><td class=\"cl-1d6de7c4\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Speargun</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7ba\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Bahari</span></p></td><td class=\"cl-1d6de7bb\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2020-04-08 00:00:00</span></p></td><td class=\"cl-1d6de7bc\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Siganus sutor</span></p></td><td class=\"cl-1d6de7bd\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">12.0</span></p></td><td class=\"cl-1d6de7be\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">12</span></p></td><td class=\"cl-1d6de7c4\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Traps</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7ba\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Bahari</span></p></td><td class=\"cl-1d6de7bb\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2020-07-25 00:00:00</span></p></td><td class=\"cl-1d6de7bc\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Siganus sutor</span></p></td><td class=\"cl-1d6de7bd\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">14.2</span></p></td><td class=\"cl-1d6de7be\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">15</span></p></td><td class=\"cl-1d6de7c4\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Traps</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7c5\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Pwani</span></p></td><td class=\"cl-1d6de7c6\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2019-07-11 00:00:00</span></p></td><td class=\"cl-1d6de7ce\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Calotomus carolinus</span></p></td><td class=\"cl-1d6de7cf\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">17.0</span></p></td><td class=\"cl-1d6de7d0\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">18</span></p></td><td class=\"cl-1d6de7d1\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Beach seine</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7ba\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Pwani</span></p></td><td class=\"cl-1d6de7bb\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2019-07-11 00:00:00</span></p></td><td class=\"cl-1d6de7bc\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Calotomus carolinus</span></p></td><td class=\"cl-1d6de7bd\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">14.3</span></p></td><td class=\"cl-1d6de7be\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">15</span></p></td><td class=\"cl-1d6de7c4\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Speargun</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7ba\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Pwani</span></p></td><td class=\"cl-1d6de7bb\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2019-05-30 00:00:00</span></p></td><td class=\"cl-1d6de7bc\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Leptoscarus vaigiensis</span></p></td><td class=\"cl-1d6de7bd\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">16.5</span></p></td><td class=\"cl-1d6de7be\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">18</span></p></td><td class=\"cl-1d6de7c4\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Speargun</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7ba\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Pwani</span></p></td><td class=\"cl-1d6de7bb\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2019-05-30 00:00:00</span></p></td><td class=\"cl-1d6de7bc\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Leptoscarus vaigiensis</span></p></td><td class=\"cl-1d6de7bd\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">30.0</span></p></td><td class=\"cl-1d6de7be\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">30</span></p></td><td class=\"cl-1d6de7c4\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Speargun</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7c5\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Pwani</span></p></td><td class=\"cl-1d6de7c6\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2019-07-11 00:00:00</span></p></td><td class=\"cl-1d6de7ce\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Calotomus carolinus</span></p></td><td class=\"cl-1d6de7cf\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">18.0</span></p></td><td class=\"cl-1d6de7d0\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">18</span></p></td><td class=\"cl-1d6de7d1\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Beach seine</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7d8\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Pwani</span></p></td><td class=\"cl-1d6de7d9\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2019-05-30 00:00:00</span></p></td><td class=\"cl-1d6de7da\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Lethrinus mahsena</span></p></td><td class=\"cl-1d6de7e2\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">12.0</span></p></td><td class=\"cl-1d6de7e3\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">12</span></p></td><td class=\"cl-1d6de7e4\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">hook and line</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7ba\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Bahari</span></p></td><td class=\"cl-1d6de7bb\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2020-07-25 00:00:00</span></p></td><td class=\"cl-1d6de7bc\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Siganus sutor</span></p></td><td class=\"cl-1d6de7bd\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">14.3</span></p></td><td class=\"cl-1d6de7be\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">15</span></p></td><td class=\"cl-1d6de7c4\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Traps</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7c5\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Pwani</span></p></td><td class=\"cl-1d6de7c6\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2019-07-11 00:00:00</span></p></td><td class=\"cl-1d6de7ce\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Calotomus carolinus</span></p></td><td class=\"cl-1d6de7cf\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">16.0</span></p></td><td class=\"cl-1d6de7d0\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">18</span></p></td><td class=\"cl-1d6de7d1\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Beach seine</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7c5\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Pwani</span></p></td><td class=\"cl-1d6de7c6\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2019-07-11 00:00:00</span></p></td><td class=\"cl-1d6de7ce\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Calotomus carolinus</span></p></td><td class=\"cl-1d6de7cf\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">13.5</span></p></td><td class=\"cl-1d6de7d0\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">15</span></p></td><td class=\"cl-1d6de7d1\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Beach seine</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7c5\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Pwani</span></p></td><td class=\"cl-1d6de7c6\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2019-07-11 00:00:00</span></p></td><td class=\"cl-1d6de7ce\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Calotomus carolinus</span></p></td><td class=\"cl-1d6de7cf\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">9.5</span></p></td><td class=\"cl-1d6de7d0\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">12</span></p></td><td class=\"cl-1d6de7d1\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Beach seine</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7d8\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Pwani</span></p></td><td class=\"cl-1d6de7d9\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2019-05-30 00:00:00</span></p></td><td class=\"cl-1d6de7da\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Lethrinus mahsena</span></p></td><td class=\"cl-1d6de7e2\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">14.0</span></p></td><td class=\"cl-1d6de7e3\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">15</span></p></td><td class=\"cl-1d6de7e4\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">hook and line</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7c5\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Pwani</span></p></td><td class=\"cl-1d6de7c6\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2019-07-11 00:00:00</span></p></td><td class=\"cl-1d6de7ce\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Calotomus carolinus</span></p></td><td class=\"cl-1d6de7cf\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">17.5</span></p></td><td class=\"cl-1d6de7d0\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">18</span></p></td><td class=\"cl-1d6de7d1\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Beach seine</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1d6de7ec\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Bahari</span></p></td><td class=\"cl-1d6de7ed\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">2020-07-25 00:00:00</span></p></td><td class=\"cl-1d6de7ee\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Siganus sutor</span></p></td><td class=\"cl-1d6de7ef\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">15.6</span></p></td><td class=\"cl-1d6de7f6\"><p class=\"cl-1d6dd63a\"><span class=\"cl-1d6a96f0\">18</span></p></td><td class=\"cl-1d6de7f7\"><p class=\"cl-1d6dd630\"><span class=\"cl-1d6a96f0\">Traps</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n### Dropping and keeping variables\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlfq.time %>% \n  select(-date)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 779 × 8\n   landing_site   day month  year species           size_cm size_class gear_type\n   <chr>        <int> <dbl> <dbl> <chr>               <dbl>      <dbl> <chr>    \n 1 Pwani           30     5  2019 Siganus sutor        16.5         18 Speargun \n 2 Pwani           30     5  2019 Siganus sutor        12           12 Speargun \n 3 Pwani           30     5  2019 Siganus sutor        15           15 Speargun \n 4 Pwani           30     5  2019 Siganus sutor        33           33 Speargun \n 5 Pwani           30     5  2019 Siganus sutor        11.2         12 hook and…\n 6 Pwani           30     5  2019 Siganus sutor        17           18 hook and…\n 7 Pwani           30     5  2019 Siganus sutor        19           21 Gill net \n 8 Pwani           30     5  2019 Lethrinus mahsena    10           12 Traps    \n 9 Pwani           30     5  2019 Lethrinus mahsena    11           12 Traps    \n10 Pwani           30     5  2019 Lethrinus mahsena     9           12 Traps    \n# ℹ 769 more rows\n```\n\n\n:::\n:::\n\n\n\n### Missing values\n\nR handles missing values differently than some other programs, including Stata. Missing values will appear as NA (whereas in Stata these will appear as large numeric values). Note, though, that NA is not a string, it is a symbol. If you try to conduct logical tests with NA, you are likely to get errors or NULL.\n\n## Length frequency\n\nLet's first look at the length data from the catch, which gives an indication of the size structure and health of the population. Using several case studies, we will filter the dataset to choose certain species and then plot histograms of the length data, which reveal the number of individual of each size class were measured in a sample or catch data.\n\nYou have several options for dealing with `NA` values.\n-   `na.omit()` or `na.exclude()` will row-wise delete missing values in your dataset\n-   `na.fail()` will keep an object only if no missing values are present\n-   `na.action=` is a common option in many functions, for example in a linear model where you might write `model <- lm(y~x, data = data, na.action = na.omit)`.\n-   `is.na` allows you to logically test for `NA` values, for example when subsetting\n\n\n### Merging and combining data\nYou may want to draw on data from multiple sources or at differing levels of aggregation. To do this, you first must know what your data look like and know what format you ultimately want them to take. Whatever you do, do not attempt to merge datasets by hand—this leads to mistakes and frustration.\n\nleft join\nbind_row\nbind_col\n\n### Reshaping data\nReshaping data into different formats is a common task. With rectangular type data (data frames have the same number of rows in each column) there are two main data frame shapes that you will come across: the `long` format (sometimes called stacked) and the `wide` format [@tidyr]. An example of a long format data frame is given in @tbl-long1. We can see that each row is a single observation from an individual species and each species can have multiple rows with different values of year and catch.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\n\naa = read_csv(\"../data/tidy/fao_capture.csv\")  %>% \n  sample_n(size = 5) %>% \n  separate(col = 'ASFIS species', into = c(\"english_name\", \"species\"), sep = \"-\") %>% dplyr::select(1:2, 7:10) \n```\n:::\n\n::: {#tbl-long1 .cell tbl-cap='Long format data frame data format'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-1dcee18c{}.cl-1dc6a152{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-1dc97e9a{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-1dc994c0{width:1.754in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dc994ca{width:1.763in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dc994d4{width:0.625in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dc994d5{width:0.905in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dc994d6{width:1.754in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dc994d7{width:1.763in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dc994de{width:0.625in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dc994df{width:0.905in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dc994e0{width:1.754in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dc994e1{width:1.763in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dc994e2{width:0.625in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dc994e8{width:0.905in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dc994f2{width:1.754in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dc994f3{width:1.763in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dc994f4{width:0.625in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dc994f5{width:0.905in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dc994fc{width:1.754in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dc994fd{width:1.763in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dc99506{width:0.625in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dc99507{width:0.905in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dc99510{width:1.754in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dc99511{width:1.763in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dc99512{width:0.625in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dc99513{width:0.905in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-1dcee18c'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-1dc994c0\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">english_name</span></p></th><th class=\"cl-1dc994ca\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">species</span></p></th><th class=\"cl-1dc994d4\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">year</span></p></th><th class=\"cl-1dc994d5\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">catch_mt</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1dc994d6\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Round sardinella</span></p></td><td class=\"cl-1dc994d7\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Sardinella aurita</span></p></td><td class=\"cl-1dc994de\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">2016</span></p></td><td class=\"cl-1dc994df\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">123 377</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1dc994d6\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Round sardinella</span></p></td><td class=\"cl-1dc994d7\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Sardinella aurita</span></p></td><td class=\"cl-1dc994de\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">2017</span></p></td><td class=\"cl-1dc994df\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">126 766</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1dc994d6\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Round sardinella</span></p></td><td class=\"cl-1dc994d7\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Sardinella aurita</span></p></td><td class=\"cl-1dc994de\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">2018</span></p></td><td class=\"cl-1dc994df\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">126 400</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1dc994d6\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Round sardinella</span></p></td><td class=\"cl-1dc994d7\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Sardinella aurita</span></p></td><td class=\"cl-1dc994de\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">2019</span></p></td><td class=\"cl-1dc994df\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">126 400</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1dc994e0\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Mexican four</span></p></td><td class=\"cl-1dc994e1\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">eyed octopus</span></p></td><td class=\"cl-1dc994e2\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">2016</span></p></td><td class=\"cl-1dc994e8\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">25 722</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1dc994e0\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Mexican four</span></p></td><td class=\"cl-1dc994e1\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">eyed octopus</span></p></td><td class=\"cl-1dc994e2\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">2017</span></p></td><td class=\"cl-1dc994e8\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">26 020</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1dc994e0\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Mexican four</span></p></td><td class=\"cl-1dc994e1\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">eyed octopus</span></p></td><td class=\"cl-1dc994e2\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">2018</span></p></td><td class=\"cl-1dc994e8\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">28809</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1dc994e0\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Mexican four</span></p></td><td class=\"cl-1dc994e1\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">eyed octopus</span></p></td><td class=\"cl-1dc994e2\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">2019</span></p></td><td class=\"cl-1dc994e8\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">20 119</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1dc994f2\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Gulf menhaden</span></p></td><td class=\"cl-1dc994f3\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Brevoortia patronus</span></p></td><td class=\"cl-1dc994f4\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">2016</span></p></td><td class=\"cl-1dc994f5\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">618 563</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1dc994f2\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Gulf menhaden</span></p></td><td class=\"cl-1dc994f3\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Brevoortia patronus</span></p></td><td class=\"cl-1dc994f4\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">2017</span></p></td><td class=\"cl-1dc994f5\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">461 189</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1dc994f2\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Gulf menhaden</span></p></td><td class=\"cl-1dc994f3\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Brevoortia patronus</span></p></td><td class=\"cl-1dc994f4\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">2018</span></p></td><td class=\"cl-1dc994f5\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">529 231</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1dc994f2\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Gulf menhaden</span></p></td><td class=\"cl-1dc994f3\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Brevoortia patronus</span></p></td><td class=\"cl-1dc994f4\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">2019</span></p></td><td class=\"cl-1dc994f5\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">336 221</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1dc994fc\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Stromboid conchs nei</span></p></td><td class=\"cl-1dc994fd\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Strombus spp</span></p></td><td class=\"cl-1dc99506\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">2016</span></p></td><td class=\"cl-1dc99507\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">28 774</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1dc994fc\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Stromboid conchs nei</span></p></td><td class=\"cl-1dc994fd\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Strombus spp</span></p></td><td class=\"cl-1dc99506\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">2017</span></p></td><td class=\"cl-1dc99507\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">35 273</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1dc994fc\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Stromboid conchs nei</span></p></td><td class=\"cl-1dc994fd\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Strombus spp</span></p></td><td class=\"cl-1dc99506\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">2018</span></p></td><td class=\"cl-1dc99507\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">34 856</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1dc994fc\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Stromboid conchs nei</span></p></td><td class=\"cl-1dc994fd\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Strombus spp</span></p></td><td class=\"cl-1dc99506\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">2019</span></p></td><td class=\"cl-1dc99507\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">28 308</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1dc994e0\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Atlantic seabob</span></p></td><td class=\"cl-1dc994e1\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Xiphopenaeus kroyeri</span></p></td><td class=\"cl-1dc994e2\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">2016</span></p></td><td class=\"cl-1dc994e8\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">30 147</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1dc994e0\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Atlantic seabob</span></p></td><td class=\"cl-1dc994e1\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Xiphopenaeus kroyeri</span></p></td><td class=\"cl-1dc994e2\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">2017</span></p></td><td class=\"cl-1dc994e8\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">31 319</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1dc994e0\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Atlantic seabob</span></p></td><td class=\"cl-1dc994e1\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Xiphopenaeus kroyeri</span></p></td><td class=\"cl-1dc994e2\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">2018</span></p></td><td class=\"cl-1dc994e8\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">31 625</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1dc99510\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Atlantic seabob</span></p></td><td class=\"cl-1dc99511\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">Xiphopenaeus kroyeri</span></p></td><td class=\"cl-1dc99512\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">2019</span></p></td><td class=\"cl-1dc99513\"><p class=\"cl-1dc97e9a\"><span class=\"cl-1dc6a152\">22 497</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\nWe can also format the same data in the wide format as in @tbl-wide. In this format the year are treated as variables and catches are values within the years.\n\n\n::: {#tbl-wide .cell tbl-cap='Wide format data frame data format'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-1deeb76e{}.cl-1de71f68{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-1de9f26a{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-1dea1196{width:1.754in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dea11a0{width:1.763in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dea11a1{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dea11a2{width:1.754in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dea11aa{width:1.763in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dea11ab{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dea11ac{width:1.754in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dea11b4{width:1.763in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dea11b5{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dea11be{width:1.754in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dea11bf{width:1.763in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dea11c0{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dea11c8{width:1.754in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dea11c9{width:1.763in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dea11d2{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dea11d3{width:1.754in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dea11d4{width:1.763in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1dea11dc{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-1deeb76e'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-1dea1196\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">english_name</span></p></th><th class=\"cl-1dea11a0\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">species</span></p></th><th class=\"cl-1dea11a1\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">2016</span></p></th><th class=\"cl-1dea11a1\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">2017</span></p></th><th class=\"cl-1dea11a1\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">2018</span></p></th><th class=\"cl-1dea11a1\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">2019</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1dea11a2\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">Round sardinella</span></p></td><td class=\"cl-1dea11aa\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">Sardinella aurita</span></p></td><td class=\"cl-1dea11ab\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">123 377</span></p></td><td class=\"cl-1dea11ab\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">126 766</span></p></td><td class=\"cl-1dea11ab\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">126 400</span></p></td><td class=\"cl-1dea11ab\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">126 400</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1dea11ac\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">Mexican four</span></p></td><td class=\"cl-1dea11b4\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">eyed octopus</span></p></td><td class=\"cl-1dea11b5\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">25 722</span></p></td><td class=\"cl-1dea11b5\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">26 020</span></p></td><td class=\"cl-1dea11b5\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">28809</span></p></td><td class=\"cl-1dea11b5\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">20 119</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1dea11be\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">Gulf menhaden</span></p></td><td class=\"cl-1dea11bf\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">Brevoortia patronus</span></p></td><td class=\"cl-1dea11c0\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">618 563</span></p></td><td class=\"cl-1dea11c0\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">461 189</span></p></td><td class=\"cl-1dea11c0\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">529 231</span></p></td><td class=\"cl-1dea11c0\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">336 221</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1dea11c8\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">Stromboid conchs nei</span></p></td><td class=\"cl-1dea11c9\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">Strombus spp</span></p></td><td class=\"cl-1dea11d2\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">28 774</span></p></td><td class=\"cl-1dea11d2\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">35 273</span></p></td><td class=\"cl-1dea11d2\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">34 856</span></p></td><td class=\"cl-1dea11d2\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">28 308</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1dea11d3\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">Atlantic seabob</span></p></td><td class=\"cl-1dea11d4\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">Xiphopenaeus kroyeri</span></p></td><td class=\"cl-1dea11dc\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">30 147</span></p></td><td class=\"cl-1dea11dc\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">31 319</span></p></td><td class=\"cl-1dea11dc\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">31 625</span></p></td><td class=\"cl-1dea11dc\"><p class=\"cl-1de9f26a\"><span class=\"cl-1de71f68\">22 497</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\n\nWhilst there’s no inherent problem with either of these formats we will sometimes need to convert between the two because some functions will require a specific format for them to work. But for the modern tidyverse function, only the dataset that is `long` format accepted.\n\nThere are many ways to convert between these two formats but we’ll use the `pivot_longer()` and `pivot_wider()` functions from the **tidyr** package [@tidyr]. We will use `fao_capture.csv` dataset in this session, we can simply load it with `read_csv` function and specify the path our dataset reside;\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncapture.wide = read_csv(\"../data/tidy/fao_capture.csv\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncapture.wide  |> \n  flextable::flextable() |> \n  flextable::autofit()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-1e2c4e62{}.cl-1e24284a{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-1e273c38{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-1e275128{width:3.41in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e275132{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e275133{width:3.41in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e275134{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e27513c{width:3.41in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e275146{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e275147{width:3.41in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e275148{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e275150{width:3.41in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e275151{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e275152{width:3.41in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e27515a{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e27515b{width:3.41in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e27515c{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e275164{width:3.41in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e275165{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e275166{width:3.41in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e27516e{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-1e2c4e62'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-1e275128\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">ASFIS species</span></p></th><th class=\"cl-1e275132\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">2012</span></p></th><th class=\"cl-1e275132\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">2013</span></p></th><th class=\"cl-1e275132\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">2014</span></p></th><th class=\"cl-1e275132\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">2015</span></p></th><th class=\"cl-1e275132\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">2016</span></p></th><th class=\"cl-1e275132\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">2017</span></p></th><th class=\"cl-1e275132\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">2018</span></p></th><th class=\"cl-1e275132\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">2019</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e275133\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">Marine fishes nei-Osteichthyes</span></p></td><td class=\"cl-1e275134\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">137 683</span></p></td><td class=\"cl-1e275134\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">112 095</span></p></td><td class=\"cl-1e275134\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">110 535</span></p></td><td class=\"cl-1e275134\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">118 078</span></p></td><td class=\"cl-1e275134\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">118 204</span></p></td><td class=\"cl-1e275134\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">124 895</span></p></td><td class=\"cl-1e275134\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">109 938</span></p></td><td class=\"cl-1e275134\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">415 031</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e27513c\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">Gulf menhaden-Brevoortia patronus</span></p></td><td class=\"cl-1e275146\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">500 162</span></p></td><td class=\"cl-1e275146\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">440 709</span></p></td><td class=\"cl-1e275146\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">385 022</span></p></td><td class=\"cl-1e275146\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">539 198</span></p></td><td class=\"cl-1e275146\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">618 563</span></p></td><td class=\"cl-1e275146\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">461 189</span></p></td><td class=\"cl-1e275146\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">529 231</span></p></td><td class=\"cl-1e275146\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">336 221</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e275147\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">Round sardinella-Sardinella aurita</span></p></td><td class=\"cl-1e275148\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">42 344</span></p></td><td class=\"cl-1e275148\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">46 299</span></p></td><td class=\"cl-1e275148\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">50 698</span></p></td><td class=\"cl-1e275148\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">79 851</span></p></td><td class=\"cl-1e275148\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">123 377</span></p></td><td class=\"cl-1e275148\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">126 766</span></p></td><td class=\"cl-1e275148\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">126 400</span></p></td><td class=\"cl-1e275148\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">126 400</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e275150\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">American cupped oyster-Crassostrea virginica</span></p></td><td class=\"cl-1e275151\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">77 900</span></p></td><td class=\"cl-1e275151\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">53 866</span></p></td><td class=\"cl-1e275151\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">57 930</span></p></td><td class=\"cl-1e275151\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">55 041</span></p></td><td class=\"cl-1e275151\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">44 313</span></p></td><td class=\"cl-1e275151\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">78 961</span></p></td><td class=\"cl-1e275151\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">49 631</span></p></td><td class=\"cl-1e275151\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">47 723</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e275152\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">Ark clams nei-Arca spp</span></p></td><td class=\"cl-1e27515a\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">12 687</span></p></td><td class=\"cl-1e27515a\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">15 000</span></p></td><td class=\"cl-1e27515a\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">17 384</span></p></td><td class=\"cl-1e27515a\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">29 073</span></p></td><td class=\"cl-1e27515a\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">29 076</span></p></td><td class=\"cl-1e27515a\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">29 970</span></p></td><td class=\"cl-1e27515a\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">29 970</span></p></td><td class=\"cl-1e27515a\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">29 970</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e27513c\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">Stromboid conchs nei-Strombus spp</span></p></td><td class=\"cl-1e275146\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">36 855</span></p></td><td class=\"cl-1e275146\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">36 610</span></p></td><td class=\"cl-1e275146\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">30 691</span></p></td><td class=\"cl-1e275146\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">34 388</span></p></td><td class=\"cl-1e275146\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">28 774</span></p></td><td class=\"cl-1e275146\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">35 273</span></p></td><td class=\"cl-1e275146\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">34 856</span></p></td><td class=\"cl-1e275146\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">28 308</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e27513c\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">Blue crab-Callinectes sapidus</span></p></td><td class=\"cl-1e275146\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">43 997</span></p></td><td class=\"cl-1e275146\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">40 570</span></p></td><td class=\"cl-1e275146\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">44 361</span></p></td><td class=\"cl-1e275146\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">50 781</span></p></td><td class=\"cl-1e275146\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">53 616</span></p></td><td class=\"cl-1e275146\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">54 628</span></p></td><td class=\"cl-1e275146\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">56 689</span></p></td><td class=\"cl-1e275146\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">25 937</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e27515b\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">Yellowfin tuna-Thunnus albacares</span></p></td><td class=\"cl-1e27515c\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">19 087</span></p></td><td class=\"cl-1e27515c\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">21 865</span></p></td><td class=\"cl-1e27515c\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">25 831</span></p></td><td class=\"cl-1e27515c\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">27 036</span></p></td><td class=\"cl-1e27515c\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">34487</span></p></td><td class=\"cl-1e27515c\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">29 310</span></p></td><td class=\"cl-1e27515c\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">30 966</span></p></td><td class=\"cl-1e27515c\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">24 503</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e275150\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">Caribbean spiny lobster-Panulirus argus</span></p></td><td class=\"cl-1e275151\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">31 102</span></p></td><td class=\"cl-1e275151\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">28 468</span></p></td><td class=\"cl-1e275151\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">28 298</span></p></td><td class=\"cl-1e275151\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">31 358</span></p></td><td class=\"cl-1e275151\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">32 410</span></p></td><td class=\"cl-1e275151\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">30 204</span></p></td><td class=\"cl-1e275151\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">28 325</span></p></td><td class=\"cl-1e275151\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">24 311</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e275164\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">Atlantic seabob-Xiphopenaeus kroyeri</span></p></td><td class=\"cl-1e275165\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">36 073</span></p></td><td class=\"cl-1e275165\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">34 243</span></p></td><td class=\"cl-1e275165\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">25 203</span></p></td><td class=\"cl-1e275165\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">25 322</span></p></td><td class=\"cl-1e275165\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">30 147</span></p></td><td class=\"cl-1e275165\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">31 319</span></p></td><td class=\"cl-1e275165\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">31 625</span></p></td><td class=\"cl-1e275165\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">22 497</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e275166\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">Mexican four-eyed octopus-Octopus maya</span></p></td><td class=\"cl-1e27516e\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">12 629</span></p></td><td class=\"cl-1e27516e\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">8 806</span></p></td><td class=\"cl-1e27516e\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">15 403</span></p></td><td class=\"cl-1e27516e\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">23 441</span></p></td><td class=\"cl-1e27516e\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">25 722</span></p></td><td class=\"cl-1e27516e\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">26 020</span></p></td><td class=\"cl-1e27516e\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">28809</span></p></td><td class=\"cl-1e27516e\"><p class=\"cl-1e273c38\"><span class=\"cl-1e24284a\">20 119</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\nThe `capture.wide`object we just created is the dataframe but is in wide format. To change from wide to long format data table, we use the `pivot_longer` function. The first argument specified in `pivot_longer` is `cols = 2:9` are index value of the variable in column 2 to colum 9 of the dataset we want to stack, `names_to = \"year\"` argument specify that the stacked variables will all be under a new variable name called `year` and the values in the stacked variables will all be under one variable called `catch`\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncapture.long = capture.wide %>% \n  pivot_longer(cols = 2:9, names_to = \"year\", values_to = \"catch\")\n```\n:::\n\n::: {#tbl-long2 .cell tbl-cap='Data values arranged in tidy wide format'}\n\n```{.r .cell-code}\ncapture.long |> \n  FSA::headtail(n = 4) |> \n  flextable::flextable() |> \n  flextable::autofit()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-1e4af57e{}.cl-1e4481a8{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-1e46f186{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-1e46ff78{width:3.155in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e46ff82{width:0.625in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e46ff83{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e46ff8c{width:3.155in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e46ff8d{width:0.625in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e46ff8e{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e46ff8f{width:3.155in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e46ff96{width:0.625in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e46ff97{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-1e4af57e'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-1e46ff78\"><p class=\"cl-1e46f186\"><span class=\"cl-1e4481a8\">ASFIS species</span></p></th><th class=\"cl-1e46ff82\"><p class=\"cl-1e46f186\"><span class=\"cl-1e4481a8\">year</span></p></th><th class=\"cl-1e46ff83\"><p class=\"cl-1e46f186\"><span class=\"cl-1e4481a8\">catch</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e46ff8c\"><p class=\"cl-1e46f186\"><span class=\"cl-1e4481a8\">Marine fishes nei-Osteichthyes</span></p></td><td class=\"cl-1e46ff8d\"><p class=\"cl-1e46f186\"><span class=\"cl-1e4481a8\">2012</span></p></td><td class=\"cl-1e46ff8e\"><p class=\"cl-1e46f186\"><span class=\"cl-1e4481a8\">137 683</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e46ff8c\"><p class=\"cl-1e46f186\"><span class=\"cl-1e4481a8\">Marine fishes nei-Osteichthyes</span></p></td><td class=\"cl-1e46ff8d\"><p class=\"cl-1e46f186\"><span class=\"cl-1e4481a8\">2013</span></p></td><td class=\"cl-1e46ff8e\"><p class=\"cl-1e46f186\"><span class=\"cl-1e4481a8\">112 095</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e46ff8c\"><p class=\"cl-1e46f186\"><span class=\"cl-1e4481a8\">Marine fishes nei-Osteichthyes</span></p></td><td class=\"cl-1e46ff8d\"><p class=\"cl-1e46f186\"><span class=\"cl-1e4481a8\">2014</span></p></td><td class=\"cl-1e46ff8e\"><p class=\"cl-1e46f186\"><span class=\"cl-1e4481a8\">110 535</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e46ff8c\"><p class=\"cl-1e46f186\"><span class=\"cl-1e4481a8\">Marine fishes nei-Osteichthyes</span></p></td><td class=\"cl-1e46ff8d\"><p class=\"cl-1e46f186\"><span class=\"cl-1e4481a8\">2015</span></p></td><td class=\"cl-1e46ff8e\"><p class=\"cl-1e46f186\"><span class=\"cl-1e4481a8\">118 078</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e46ff8c\"><p class=\"cl-1e46f186\"><span class=\"cl-1e4481a8\">Mexican four-eyed octopus-Octopus maya</span></p></td><td class=\"cl-1e46ff8d\"><p class=\"cl-1e46f186\"><span class=\"cl-1e4481a8\">2016</span></p></td><td class=\"cl-1e46ff8e\"><p class=\"cl-1e46f186\"><span class=\"cl-1e4481a8\">25 722</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e46ff8c\"><p class=\"cl-1e46f186\"><span class=\"cl-1e4481a8\">Mexican four-eyed octopus-Octopus maya</span></p></td><td class=\"cl-1e46ff8d\"><p class=\"cl-1e46f186\"><span class=\"cl-1e4481a8\">2017</span></p></td><td class=\"cl-1e46ff8e\"><p class=\"cl-1e46f186\"><span class=\"cl-1e4481a8\">26 020</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e46ff8c\"><p class=\"cl-1e46f186\"><span class=\"cl-1e4481a8\">Mexican four-eyed octopus-Octopus maya</span></p></td><td class=\"cl-1e46ff8d\"><p class=\"cl-1e46f186\"><span class=\"cl-1e4481a8\">2018</span></p></td><td class=\"cl-1e46ff8e\"><p class=\"cl-1e46f186\"><span class=\"cl-1e4481a8\">28809</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e46ff8f\"><p class=\"cl-1e46f186\"><span class=\"cl-1e4481a8\">Mexican four-eyed octopus-Octopus maya</span></p></td><td class=\"cl-1e46ff96\"><p class=\"cl-1e46f186\"><span class=\"cl-1e4481a8\">2019</span></p></td><td class=\"cl-1e46ff97\"><p class=\"cl-1e46f186\"><span class=\"cl-1e4481a8\">20 119</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\nThe `pivot_wider()` function is used to convert from a `long` format data frame to a `wide` format data frame. The first argument is `names_from = year` is the variable of the data frame for which we want spread across and the second argument `values_from = catch` is the corresponding values will reside in each casted variable. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ncapture.wide = capture.long %>% \n  pivot_wider(names_from = year, values_from = catch)\n```\n:::\n\n::: {#tbl-long .cell tbl-cap='Data values arranged in tidy wide format'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-1e71b4fc{}.cl-1e6a2868{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-1e6d1870{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-1e6d27d4{width:3.41in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e6d27de{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e6d27df{width:3.41in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e6d27e8{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e6d27e9{width:3.41in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e6d27f2{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e6d27fc{width:3.41in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e6d27fd{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e6d27fe{width:3.41in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e6d2806{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e6d2807{width:3.41in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e6d2808{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e6d2809{width:3.41in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e6d2810{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e6d2811{width:3.41in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e6d281a{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e6d281b{width:3.41in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e6d281c{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-1e71b4fc'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-1e6d27d4\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">ASFIS species</span></p></th><th class=\"cl-1e6d27de\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">2012</span></p></th><th class=\"cl-1e6d27de\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">2013</span></p></th><th class=\"cl-1e6d27de\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">2014</span></p></th><th class=\"cl-1e6d27de\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">2015</span></p></th><th class=\"cl-1e6d27de\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">2016</span></p></th><th class=\"cl-1e6d27de\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">2017</span></p></th><th class=\"cl-1e6d27de\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">2018</span></p></th><th class=\"cl-1e6d27de\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">2019</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e6d27df\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">Marine fishes nei-Osteichthyes</span></p></td><td class=\"cl-1e6d27e8\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">137 683</span></p></td><td class=\"cl-1e6d27e8\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">112 095</span></p></td><td class=\"cl-1e6d27e8\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">110 535</span></p></td><td class=\"cl-1e6d27e8\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">118 078</span></p></td><td class=\"cl-1e6d27e8\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">118 204</span></p></td><td class=\"cl-1e6d27e8\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">124 895</span></p></td><td class=\"cl-1e6d27e8\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">109 938</span></p></td><td class=\"cl-1e6d27e8\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">415 031</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e6d27e9\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">Gulf menhaden-Brevoortia patronus</span></p></td><td class=\"cl-1e6d27f2\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">500 162</span></p></td><td class=\"cl-1e6d27f2\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">440 709</span></p></td><td class=\"cl-1e6d27f2\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">385 022</span></p></td><td class=\"cl-1e6d27f2\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">539 198</span></p></td><td class=\"cl-1e6d27f2\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">618 563</span></p></td><td class=\"cl-1e6d27f2\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">461 189</span></p></td><td class=\"cl-1e6d27f2\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">529 231</span></p></td><td class=\"cl-1e6d27f2\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">336 221</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e6d27fc\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">Round sardinella-Sardinella aurita</span></p></td><td class=\"cl-1e6d27fd\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">42 344</span></p></td><td class=\"cl-1e6d27fd\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">46 299</span></p></td><td class=\"cl-1e6d27fd\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">50 698</span></p></td><td class=\"cl-1e6d27fd\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">79 851</span></p></td><td class=\"cl-1e6d27fd\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">123 377</span></p></td><td class=\"cl-1e6d27fd\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">126 766</span></p></td><td class=\"cl-1e6d27fd\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">126 400</span></p></td><td class=\"cl-1e6d27fd\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">126 400</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e6d27fe\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">American cupped oyster-Crassostrea virginica</span></p></td><td class=\"cl-1e6d2806\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">77 900</span></p></td><td class=\"cl-1e6d2806\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">53 866</span></p></td><td class=\"cl-1e6d2806\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">57 930</span></p></td><td class=\"cl-1e6d2806\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">55 041</span></p></td><td class=\"cl-1e6d2806\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">44 313</span></p></td><td class=\"cl-1e6d2806\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">78 961</span></p></td><td class=\"cl-1e6d2806\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">49 631</span></p></td><td class=\"cl-1e6d2806\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">47 723</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e6d2807\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">Ark clams nei-Arca spp</span></p></td><td class=\"cl-1e6d2808\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">12 687</span></p></td><td class=\"cl-1e6d2808\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">15 000</span></p></td><td class=\"cl-1e6d2808\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">17 384</span></p></td><td class=\"cl-1e6d2808\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">29 073</span></p></td><td class=\"cl-1e6d2808\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">29 076</span></p></td><td class=\"cl-1e6d2808\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">29 970</span></p></td><td class=\"cl-1e6d2808\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">29 970</span></p></td><td class=\"cl-1e6d2808\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">29 970</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e6d27e9\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">Stromboid conchs nei-Strombus spp</span></p></td><td class=\"cl-1e6d27f2\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">36 855</span></p></td><td class=\"cl-1e6d27f2\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">36 610</span></p></td><td class=\"cl-1e6d27f2\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">30 691</span></p></td><td class=\"cl-1e6d27f2\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">34 388</span></p></td><td class=\"cl-1e6d27f2\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">28 774</span></p></td><td class=\"cl-1e6d27f2\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">35 273</span></p></td><td class=\"cl-1e6d27f2\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">34 856</span></p></td><td class=\"cl-1e6d27f2\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">28 308</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e6d27e9\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">Blue crab-Callinectes sapidus</span></p></td><td class=\"cl-1e6d27f2\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">43 997</span></p></td><td class=\"cl-1e6d27f2\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">40 570</span></p></td><td class=\"cl-1e6d27f2\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">44 361</span></p></td><td class=\"cl-1e6d27f2\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">50 781</span></p></td><td class=\"cl-1e6d27f2\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">53 616</span></p></td><td class=\"cl-1e6d27f2\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">54 628</span></p></td><td class=\"cl-1e6d27f2\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">56 689</span></p></td><td class=\"cl-1e6d27f2\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">25 937</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e6d2809\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">Yellowfin tuna-Thunnus albacares</span></p></td><td class=\"cl-1e6d2810\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">19 087</span></p></td><td class=\"cl-1e6d2810\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">21 865</span></p></td><td class=\"cl-1e6d2810\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">25 831</span></p></td><td class=\"cl-1e6d2810\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">27 036</span></p></td><td class=\"cl-1e6d2810\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">34487</span></p></td><td class=\"cl-1e6d2810\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">29 310</span></p></td><td class=\"cl-1e6d2810\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">30 966</span></p></td><td class=\"cl-1e6d2810\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">24 503</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e6d27fe\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">Caribbean spiny lobster-Panulirus argus</span></p></td><td class=\"cl-1e6d2806\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">31 102</span></p></td><td class=\"cl-1e6d2806\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">28 468</span></p></td><td class=\"cl-1e6d2806\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">28 298</span></p></td><td class=\"cl-1e6d2806\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">31 358</span></p></td><td class=\"cl-1e6d2806\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">32 410</span></p></td><td class=\"cl-1e6d2806\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">30 204</span></p></td><td class=\"cl-1e6d2806\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">28 325</span></p></td><td class=\"cl-1e6d2806\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">24 311</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e6d2811\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">Atlantic seabob-Xiphopenaeus kroyeri</span></p></td><td class=\"cl-1e6d281a\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">36 073</span></p></td><td class=\"cl-1e6d281a\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">34 243</span></p></td><td class=\"cl-1e6d281a\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">25 203</span></p></td><td class=\"cl-1e6d281a\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">25 322</span></p></td><td class=\"cl-1e6d281a\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">30 147</span></p></td><td class=\"cl-1e6d281a\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">31 319</span></p></td><td class=\"cl-1e6d281a\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">31 625</span></p></td><td class=\"cl-1e6d281a\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">22 497</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e6d281b\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">Mexican four-eyed octopus-Octopus maya</span></p></td><td class=\"cl-1e6d281c\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">12 629</span></p></td><td class=\"cl-1e6d281c\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">8 806</span></p></td><td class=\"cl-1e6d281c\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">15 403</span></p></td><td class=\"cl-1e6d281c\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">23 441</span></p></td><td class=\"cl-1e6d281c\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">25 722</span></p></td><td class=\"cl-1e6d281c\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">26 020</span></p></td><td class=\"cl-1e6d281c\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">28809</span></p></td><td class=\"cl-1e6d281c\"><p class=\"cl-1e6d1870\"><span class=\"cl-1e6a2868\">20 119</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n### Saving transformed data\nOnce you have transformed your data and edited variables, you may want to save your new dataframe as an external data file that your collaborators or other researchers can use. As with reading in data, for saving out data you will need the foreign package. Similarly, you can choose from a number of different data formats to export to as well. Most commonly you will want to save out data as a `.csv` or a tab-delited text file.\n\n```r\nmyfile %>% write_csv(\"my.directory/file_name.csv\")\n```\n\n## Transforming, summarising, and analysing data\nThe R universe basically builds upon two (seemingly contradictive) approaches: base R and the tidyverse. While these two approaches are often seen as two different philosophies, they can form a symbiosis. We therefore recommend to pick whichever works best for you – or to combine the two.Whereas base R is already implemented in R, using the tidyverse requires users to load new packages. People often find base R unintuitive and hard to read. This is why Hadley Wickham developed and introduced the tidyverse – a more intuitive approach to managing and wrangling data [@tidyverse].\n\nCode written before 2014 was usually written in base R whereas the tidyverse style is becoming increasingly widespread. Again, which approach you prefer is rather a matter of personal taste than a decision between “right or wrong”. We first familiarize ourselves with the basic logic of the tidyverse style using some examples. For this, we use `LFQ_sample_1.xls`. since is an Excel format, lets import it in our session;\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlfq.sample1 = readxl::read_excel(\"../data/LFQ_sample_1.xls\")\n```\n:::\n\n\nLet's print the assigned lfq.sample1\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlfq.sample1 |> \n  FSA::headtail() |> \n  flextable::flextable() |> \n  flextable::autofit()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-1e967102{}.cl-1e8d126a{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-1e909610{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-1e909624{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-1e90bc80{width:1.704in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e90bc8a{width:1.678in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e90bc94{width:0.93in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e90bc95{width:1.007in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e90bc9e{width:0.956in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e90bc9f{width:1.152in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e90bca8{width:1.704in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e90bcb2{width:1.678in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e90bcb3{width:0.93in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e90bcbc{width:1.007in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e90bcbd{width:0.956in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e90bcbe{width:1.152in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e90bcc6{width:1.704in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e90bcc7{width:1.678in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e90bcd0{width:0.93in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e90bcd1{width:1.007in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e90bcda{width:0.956in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e90bcdb{width:1.152in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-1e967102'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-1e90bc80\"><p class=\"cl-1e909610\"><span class=\"cl-1e8d126a\">Date</span></p></th><th class=\"cl-1e90bc8a\"><p class=\"cl-1e909624\"><span class=\"cl-1e8d126a\">Species</span></p></th><th class=\"cl-1e90bc94\"><p class=\"cl-1e909610\"><span class=\"cl-1e8d126a\">Size (cm)</span></p></th><th class=\"cl-1e90bc95\"><p class=\"cl-1e909610\"><span class=\"cl-1e8d126a\">Size Class</span></p></th><th class=\"cl-1e90bc9e\"><p class=\"cl-1e909624\"><span class=\"cl-1e8d126a\">Gear type</span></p></th><th class=\"cl-1e90bc9f\"><p class=\"cl-1e909624\"><span class=\"cl-1e8d126a\">Landing_site</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e90bca8\"><p class=\"cl-1e909610\"><span class=\"cl-1e8d126a\">2019-05-30 00:00:00</span></p></td><td class=\"cl-1e90bcb2\"><p class=\"cl-1e909624\"><span class=\"cl-1e8d126a\">Siganus sutor</span></p></td><td class=\"cl-1e90bcb3\"><p class=\"cl-1e909610\"><span class=\"cl-1e8d126a\">16.5</span></p></td><td class=\"cl-1e90bcbc\"><p class=\"cl-1e909610\"><span class=\"cl-1e8d126a\">18</span></p></td><td class=\"cl-1e90bcbd\"><p class=\"cl-1e909624\"><span class=\"cl-1e8d126a\">Speargun</span></p></td><td class=\"cl-1e90bcbe\"><p class=\"cl-1e909624\"><span class=\"cl-1e8d126a\">Pwani</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e90bca8\"><p class=\"cl-1e909610\"><span class=\"cl-1e8d126a\">2019-05-30 00:00:00</span></p></td><td class=\"cl-1e90bcb2\"><p class=\"cl-1e909624\"><span class=\"cl-1e8d126a\">Siganus sutor</span></p></td><td class=\"cl-1e90bcb3\"><p class=\"cl-1e909610\"><span class=\"cl-1e8d126a\">12.0</span></p></td><td class=\"cl-1e90bcbc\"><p class=\"cl-1e909610\"><span class=\"cl-1e8d126a\">12</span></p></td><td class=\"cl-1e90bcbd\"><p class=\"cl-1e909624\"><span class=\"cl-1e8d126a\">Speargun</span></p></td><td class=\"cl-1e90bcbe\"><p class=\"cl-1e909624\"><span class=\"cl-1e8d126a\">Pwani</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e90bca8\"><p class=\"cl-1e909610\"><span class=\"cl-1e8d126a\">2019-05-30 00:00:00</span></p></td><td class=\"cl-1e90bcb2\"><p class=\"cl-1e909624\"><span class=\"cl-1e8d126a\">Siganus sutor</span></p></td><td class=\"cl-1e90bcb3\"><p class=\"cl-1e909610\"><span class=\"cl-1e8d126a\">15.0</span></p></td><td class=\"cl-1e90bcbc\"><p class=\"cl-1e909610\"><span class=\"cl-1e8d126a\">15</span></p></td><td class=\"cl-1e90bcbd\"><p class=\"cl-1e909624\"><span class=\"cl-1e8d126a\">Speargun</span></p></td><td class=\"cl-1e90bcbe\"><p class=\"cl-1e909624\"><span class=\"cl-1e8d126a\">Pwani</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e90bca8\"><p class=\"cl-1e909610\"><span class=\"cl-1e8d126a\">2020-07-25 00:00:00</span></p></td><td class=\"cl-1e90bcb2\"><p class=\"cl-1e909624\"><span class=\"cl-1e8d126a\">Lutjanus fulviflamma</span></p></td><td class=\"cl-1e90bcb3\"><p class=\"cl-1e909610\"><span class=\"cl-1e8d126a\">13.0</span></p></td><td class=\"cl-1e90bcbc\"><p class=\"cl-1e909610\"><span class=\"cl-1e8d126a\">15</span></p></td><td class=\"cl-1e90bcbd\"><p class=\"cl-1e909624\"><span class=\"cl-1e8d126a\">Speargun</span></p></td><td class=\"cl-1e90bcbe\"><p class=\"cl-1e909624\"><span class=\"cl-1e8d126a\">Bahari</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e90bca8\"><p class=\"cl-1e909610\"><span class=\"cl-1e8d126a\">2020-07-25 00:00:00</span></p></td><td class=\"cl-1e90bcb2\"><p class=\"cl-1e909624\"><span class=\"cl-1e8d126a\">Lutjanus fulviflamma</span></p></td><td class=\"cl-1e90bcb3\"><p class=\"cl-1e909610\"><span class=\"cl-1e8d126a\">17.0</span></p></td><td class=\"cl-1e90bcbc\"><p class=\"cl-1e909610\"><span class=\"cl-1e8d126a\">18</span></p></td><td class=\"cl-1e90bcbd\"><p class=\"cl-1e909624\"><span class=\"cl-1e8d126a\">Speargun</span></p></td><td class=\"cl-1e90bcbe\"><p class=\"cl-1e909624\"><span class=\"cl-1e8d126a\">Bahari</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e90bcc6\"><p class=\"cl-1e909610\"><span class=\"cl-1e8d126a\">2020-07-25 00:00:00</span></p></td><td class=\"cl-1e90bcc7\"><p class=\"cl-1e909624\"><span class=\"cl-1e8d126a\">Lutjanus fulviflamma</span></p></td><td class=\"cl-1e90bcd0\"><p class=\"cl-1e909610\"><span class=\"cl-1e8d126a\">18.5</span></p></td><td class=\"cl-1e90bcd1\"><p class=\"cl-1e909610\"><span class=\"cl-1e8d126a\">21</span></p></td><td class=\"cl-1e90bcda\"><p class=\"cl-1e909624\"><span class=\"cl-1e8d126a\">Speargun</span></p></td><td class=\"cl-1e90bcdb\"><p class=\"cl-1e909624\"><span class=\"cl-1e8d126a\">Bahari</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\nAs you can see from the output generated in your console, the `lfq.sample1` data frame object contains length information of several species. The fisheries data collected in this dataset ensured that each record on a separate row and each column represents a variable. The dataset contains six variables (columns) and 779 records (rows). These variables includes;\n\n-   `Date` a sample was collected. The date is in the `YYYY-MM-DD`, which is the format that accepted\n-   `Species` the scientific name of the species\n-   `Size (cm)` the length of the fish species measured in centimeter\n-   `Size Class` of the individual\n-   `Gear type` used to catch the recorded fish, and\n-   `Landing-site` a landing station where the fish was recorded\n\nThis dataset is arranged in appropriate format. The data was entered in spreadsheet with a few basics. These correspond to: what, where, when it only miss who collect the data or the originator of this dataset. The way this dataset is organized is the classical example of how set out our data in a similar fashion. This makes manipulating the data more straightforward and also maintains the multi-purpose nature of the analysis work. Having your data organized is really important!\n\n::: callout-warning\nThough the size and unit of the dataaset is provide, but it does not tell us much because we do not know whether the measurement is total length (TL), standard length (SL) or fork length (FL). It is imperative to specify in the dataset variable names what was measured and the unit\n:::\n\n\n### Renaming variables\n\nLooking `lfq.sample1` dataset presented in @tbl-case1, we notice that variable names do not adhere to standard variable names. The tidyverse style guide recommends snake case (words separated by underscores tl_cm) for object and column names. Let's look back at our column names for a minute. Using the `names()` function from the  and pipe operator `%>%` from the **magrittr** package simultaneously serves as the first pipe in a chain of commands and print names in the dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlfq.sample1 %>% \n  names()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Date\"         \"Species\"      \"Size (cm)\"    \"Size Class\"   \"Gear type\"   \n[6] \"Landing_site\"\n```\n\n\n:::\n:::\n\n\nThere are all sorts of capital letters and spaces (e.g. \"Gear type\" ,\" \"Size Class\" ) as well as symbols (\"Size (cm)\"). Therefore we mustl convert all of these to snake case for us. We can rename specific variables using the `rename` function from the **dplyr** package [@dplyr]. Since **dplyr** is part of the **tidyverse** package [@tidyverse] that was loaded, we do not need to load it again but rather use its function to rename the variables. We'll begin by specifying the name of our data frame object `lfq.sample1`, followed by the `=` operator so that we can overwrite the existing `lfq.sample1` frame object with one that contains the renamed variables.\n\n\nNext type `lfq.sample1` followed by pipe operator `%>%` and then call a`rename` function, where you parse the new names to their corresponding old names. As the first argument, let's change the `Date` variable to `date` by typing the name of our new variable followed by = and, in quotation marks (\" \"), the name of the original variable `date = \"Date\"`. As the second argument, let's apply the same process as the second argument and change the `Species` variable to `species` by typing the name of our new variable followed by = and, in quotation marks (\" \"), the name of the original variable `species = \"Species\"`. We follow the same naming procedure to the six variables as the chunk below highlight;\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlfq.sample1 = lfq.sample1 %>% \n  rename(\n    date = \"Date\",\n    species = \"Species\",\n    size_cm = \"Size (cm)\",\n    size_class = \"Size Class\",\n    gear_type = \"Gear type\",\n    landing_site = \"Landing_site\"\n    )\n```\n:::\n\n\nUsing the head function from base R, let's verify that we renamed the two variables successfully.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlfq.sample1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 779 × 6\n   date                species         size_cm size_class gear_type landing_site\n   <dttm>              <chr>             <dbl>      <dbl> <chr>     <chr>       \n 1 2019-05-30 00:00:00 Siganus sutor      16.5         18 Speargun  Pwani       \n 2 2019-05-30 00:00:00 Siganus sutor      12           12 Speargun  Pwani       \n 3 2019-05-30 00:00:00 Siganus sutor      15           15 Speargun  Pwani       \n 4 2019-05-30 00:00:00 Siganus sutor      33           33 Speargun  Pwani       \n 5 2019-05-30 00:00:00 Siganus sutor      11.2         12 hook and… Pwani       \n 6 2019-05-30 00:00:00 Siganus sutor      17           18 hook and… Pwani       \n 7 2019-05-30 00:00:00 Siganus sutor      19           21 Gill net  Pwani       \n 8 2019-05-30 00:00:00 Lethrinus mahs…    10           12 Traps     Pwani       \n 9 2019-05-30 00:00:00 Lethrinus mahs…    11           12 Traps     Pwani       \n10 2019-05-30 00:00:00 Lethrinus mahs…     9           12 Traps     Pwani       \n# ℹ 769 more rows\n```\n\n\n:::\n:::\n\n\nAs you can see, the new names have no spaces and all are written in small letters. Spaces in variables names were replaced with the underscore symbol.\n\nThough the rename function is great tool to rename variables in the dataset, however there are times when you a dataset has hundred of variables names to change and using `rename` function from dplyr package become tedious. Furtunate , a **janitor** package has a nifty `clean_names()` function that clean all the variable names with a single line of code. I highly recommend incorporating it into your workflow.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlfq.sample1 = readxl::read_excel(\"../data/LFQ_sample_1.xls\") %>% \n  janitor::clean_names()\n\nlfq.sample1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 779 × 6\n   date                species         size_cm size_class gear_type landing_site\n   <dttm>              <chr>             <dbl>      <dbl> <chr>     <chr>       \n 1 2019-05-30 00:00:00 Siganus sutor      16.5         18 Speargun  Pwani       \n 2 2019-05-30 00:00:00 Siganus sutor      12           12 Speargun  Pwani       \n 3 2019-05-30 00:00:00 Siganus sutor      15           15 Speargun  Pwani       \n 4 2019-05-30 00:00:00 Siganus sutor      33           33 Speargun  Pwani       \n 5 2019-05-30 00:00:00 Siganus sutor      11.2         12 hook and… Pwani       \n 6 2019-05-30 00:00:00 Siganus sutor      17           18 hook and… Pwani       \n 7 2019-05-30 00:00:00 Siganus sutor      19           21 Gill net  Pwani       \n 8 2019-05-30 00:00:00 Lethrinus mahs…    10           12 Traps     Pwani       \n 9 2019-05-30 00:00:00 Lethrinus mahs…    11           12 Traps     Pwani       \n10 2019-05-30 00:00:00 Lethrinus mahs…     9           12 Traps     Pwani       \n# ℹ 769 more rows\n```\n\n\n:::\n:::\n\n\nAs you can see above, the `clean_names()` function handled every kind of messy variable name that was present in our `lfq.sample1` dataset. Everything now looks neat and tidy\n\n\n### Filtering Data\n\nOur `lfq.sample1` contains six variables -- date, species, size_cm, size_class, gear_type and landing_site;\n\n::: {.cell}\n\n```{.r .cell-code}\nlfq.sample1 %>% \n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 779\nColumns: 6\n$ date         <dttm> 2019-05-30, 2019-05-30, 2019-05-30, 2019-05-30, 2019-05-…\n$ species      <chr> \"Siganus sutor\", \"Siganus sutor\", \"Siganus sutor\", \"Sigan…\n$ size_cm      <dbl> 16.5, 12.0, 15.0, 33.0, 11.2, 17.0, 19.0, 10.0, 11.0, 9.0…\n$ size_class   <dbl> 18, 12, 15, 33, 12, 18, 21, 12, 12, 12, 12, 12, 12, 12, 1…\n$ gear_type    <chr> \"Speargun\", \"Speargun\", \"Speargun\", \"Speargun\", \"hook and…\n$ landing_site <chr> \"Pwani\", \"Pwani\", \"Pwani\", \"Pwani\", \"Pwani\", \"Pwani\", \"Pw…\n```\n\n\n:::\n:::\n\nSuppose we are only interested in *Siganus sutor* species only from the dataset. For this purpose, we can use the `filter()` function from  **dplyr** package [@dplyr]\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlfq.sample1 %>% \n  filter(species == \"Siganus sutor\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 196 × 6\n   date                species       size_cm size_class gear_type   landing_site\n   <dttm>              <chr>           <dbl>      <dbl> <chr>       <chr>       \n 1 2019-05-30 00:00:00 Siganus sutor    16.5         18 Speargun    Pwani       \n 2 2019-05-30 00:00:00 Siganus sutor    12           12 Speargun    Pwani       \n 3 2019-05-30 00:00:00 Siganus sutor    15           15 Speargun    Pwani       \n 4 2019-05-30 00:00:00 Siganus sutor    33           33 Speargun    Pwani       \n 5 2019-05-30 00:00:00 Siganus sutor    11.2         12 hook and l… Pwani       \n 6 2019-05-30 00:00:00 Siganus sutor    17           18 hook and l… Pwani       \n 7 2019-05-30 00:00:00 Siganus sutor    19           21 Gill net    Pwani       \n 8 2019-06-25 00:00:00 Siganus sutor    36.5         39 Speargun    Pwani       \n 9 2019-06-25 00:00:00 Siganus sutor    11           12 hook and l… Pwani       \n10 2019-06-25 00:00:00 Siganus sutor    11           12 hook and l… Pwani       \n# ℹ 186 more rows\n```\n\n\n:::\n:::\n\n\n### Select\nSometimes, you want to select specific variables. For instance, We are interested in three variables -- date, landing_site, species, size_cm but not so much in the other variables. A `select()` function **dplyr** package  allows you to do exactly this.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlfq.sample1 %>% \n  select(date, landing_site, species, size_cm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 779 × 4\n   date                landing_site species           size_cm\n   <dttm>              <chr>        <chr>               <dbl>\n 1 2019-05-30 00:00:00 Pwani        Siganus sutor        16.5\n 2 2019-05-30 00:00:00 Pwani        Siganus sutor        12  \n 3 2019-05-30 00:00:00 Pwani        Siganus sutor        15  \n 4 2019-05-30 00:00:00 Pwani        Siganus sutor        33  \n 5 2019-05-30 00:00:00 Pwani        Siganus sutor        11.2\n 6 2019-05-30 00:00:00 Pwani        Siganus sutor        17  \n 7 2019-05-30 00:00:00 Pwani        Siganus sutor        19  \n 8 2019-05-30 00:00:00 Pwani        Lethrinus mahsena    10  \n 9 2019-05-30 00:00:00 Pwani        Lethrinus mahsena    11  \n10 2019-05-30 00:00:00 Pwani        Lethrinus mahsena     9  \n# ℹ 769 more rows\n```\n\n\n:::\n:::\n\n\n### Arranging variables\nLet’s say we want to know the species with larges and smallest size throughout the entire dataset. This can be done with the `arrange()` function. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlfq.sample1 %>% \n  arrange(size_cm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 779 × 6\n   date                species         size_cm size_class gear_type landing_site\n   <dttm>              <chr>             <dbl>      <dbl> <chr>     <chr>       \n 1 2019-07-12 00:00:00 Lethrinus harak     6            6 Traps     Pwani       \n 2 2020-04-08 00:00:00 Lethrinus mahs…     8.3         12 Traps     Bahari      \n 3 2020-04-08 00:00:00 Lethrinus mahs…     8.4         12 Traps     Bahari      \n 4 2019-05-30 00:00:00 Lethrinus mahs…     9           12 Traps     Pwani       \n 5 2019-05-30 00:00:00 Lethrinus mahs…     9           12 Traps     Pwani       \n 6 2020-06-15 00:00:00 Siganus sutor       9           12 Traps     Bahari      \n 7 2020-06-15 00:00:00 Lethrinus harak     9           12 Traps     Bahari      \n 8 2019-05-30 00:00:00 Lethrinus mahs…     9.3         12 hook and… Pwani       \n 9 2019-05-30 00:00:00 Lethrinus mahs…     9.3         12 hook and… Pwani       \n10 2020-04-08 00:00:00 Lethrinus mahs…     9.4         12 Traps     Bahari      \n# ℹ 769 more rows\n```\n\n\n:::\n:::\n\n\nAs we can see, *Lethrinus* are the species with the smallest size in the datase. The smallest size in the dataset is 6cm.  By default, the `arrange()` function sorts the data in ascending order. To display the data in descending order, we add desc().\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlfq.sample1 %>% \n  arrange(desc(size_cm))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 779 × 6\n   date                species         size_cm size_class gear_type landing_site\n   <dttm>              <chr>             <dbl>      <dbl> <chr>     <chr>       \n 1 2019-06-25 00:00:00 Siganus sutor      36.5         39 Speargun  Pwani       \n 2 2019-05-30 00:00:00 Siganus sutor      33           33 Speargun  Pwani       \n 3 2020-04-08 00:00:00 Calotomus caro…    30.4         33 Traps     Bahari      \n 4 2020-06-15 00:00:00 Lethrinus mahs…    30.2         33 hook and… Bahari      \n 5 2019-05-30 00:00:00 Leptoscarus va…    30           30 Speargun  Pwani       \n 6 2020-04-08 00:00:00 Anampses spp.      30           30 Speargun  Bahari      \n 7 2019-07-11 00:00:00 Lutjanus fulvi…    27.5         30 hook and… Pwani       \n 8 2019-07-12 00:00:00 Siganus sutor      27.5         30 Gill net  Pwani       \n 9 2019-07-11 00:00:00 Calotomus caro…    27           27 Beach se… Pwani       \n10 2019-07-12 00:00:00 Siganus sutor      27           27 Gill net  Pwani       \n# ℹ 769 more rows\n```\n\n\n:::\n:::\n\n\nAs we can see, *Siganus sutor* are the species with the larges size in the dataset. The highest size in the dataset is 36.50cm.\n\n\n### Extracting unique observations\nWhich unique species are included in the dataset? To get this information, we use the `distinct()` function in dplyr.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlfq.sample1 %>% \n  distinct(species)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 1\n  species               \n  <chr>                 \n1 Siganus sutor         \n2 Lethrinus mahsena     \n3 Leptoscarus vaigiensis\n4 Calotomus carolinus   \n5 Lutjanus fulviflamma  \n6 Lethrinus harak       \n7 Anampses spp.         \n8 Acanthurus chronixis  \n9 Cheilinus chlorourus  \n```\n\n\n:::\n:::\n\n\nAs we see, there are nine species in the dataset arranged in the species variable of the dataframe. However, We might need these species in vector instead of data frame. We use the function `pull` for that, which convert from dataframe to vector dataset. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlfq.sample1 %>% \n  distinct(species) %>% \n  pull()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Siganus sutor\"          \"Lethrinus mahsena\"      \"Leptoscarus vaigiensis\"\n[4] \"Calotomus carolinus\"    \"Lutjanus fulviflamma\"   \"Lethrinus harak\"       \n[7] \"Anampses spp.\"          \"Acanthurus chronixis\"   \"Cheilinus chlorourus\"  \n```\n\n\n:::\n:::\n\n\n\n### Creating new variables\nThe `mutate()` command allows you to generate a new variable from existing. Let’s say you want to generate a day, month and year from date variables. The lubridate packaged [@lubridate] has functions dedicated for dealing with dates, some of these functions include `day()`, `month()`, and `year()` that are used to extract values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlfq.sample1 %>% \n  select(date, species, size_cm) %>% \n  mutate(\n    year = lubridate::year(date),\n    month = lubridate::month(date),\n    day = lubridate::day(date)\n    )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 779 × 6\n   date                species           size_cm  year month   day\n   <dttm>              <chr>               <dbl> <dbl> <dbl> <int>\n 1 2019-05-30 00:00:00 Siganus sutor        16.5  2019     5    30\n 2 2019-05-30 00:00:00 Siganus sutor        12    2019     5    30\n 3 2019-05-30 00:00:00 Siganus sutor        15    2019     5    30\n 4 2019-05-30 00:00:00 Siganus sutor        33    2019     5    30\n 5 2019-05-30 00:00:00 Siganus sutor        11.2  2019     5    30\n 6 2019-05-30 00:00:00 Siganus sutor        17    2019     5    30\n 7 2019-05-30 00:00:00 Siganus sutor        19    2019     5    30\n 8 2019-05-30 00:00:00 Lethrinus mahsena    10    2019     5    30\n 9 2019-05-30 00:00:00 Lethrinus mahsena    11    2019     5    30\n10 2019-05-30 00:00:00 Lethrinus mahsena     9    2019     5    30\n# ℹ 769 more rows\n```\n\n\n:::\n:::\n\n\n\n### Group-wise operations\nSuppose we are interested to know the sample size for each species in the dataset along with the mean, median, and standard deviation of the body size. That's is not possible with single function in the tidyverse but rather a combination of functions. We use a combination of `group_by()` (to group our results by month), and parse the specific function we want to compute in the `summarise()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlfq.sample1 %>% \n  group_by(species) %>% \n  summarise(\n    n = n(),\n    mean_cm = mean(size_cm),\n    median_cm = median(size_cm),\n    std_cm = sd(size_cm)\n    ) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 5\n  species                    n mean_cm median_cm std_cm\n  <chr>                  <int>   <dbl>     <dbl>  <dbl>\n1 Acanthurus chronixis      21    13.7      12.5  2.65 \n2 Anampses spp.             17    17.5      16.5  4.43 \n3 Calotomus carolinus      176    16.4      16.5  3.05 \n4 Cheilinus chlorourus       4    13.9      14    0.810\n5 Leptoscarus vaigiensis   146    18.1      17.5  3.53 \n6 Lethrinus harak           37    12.6      12    2.72 \n7 Lethrinus mahsena        135    11.9      11.9  2.39 \n8 Lutjanus fulviflamma      47    16.7      16.9  2.67 \n9 Siganus sutor            196    18.2      17.5  4.66 \n```\n\n\n:::\n:::\n\n\n\nThe computed variables are grouped after performing transformations. In this case, you can pipe another command with  `ungroup()` to ungroup your result.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlfq.sample1 %>% \n  group_by(species) %>% \n  summarise(\n    n = n(),\n    mean_cm = mean(size_cm),\n    median_cm = median(size_cm),\n    std_cm = sd(size_cm)\n    ) %>% \n  ungroup()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 5\n  species                    n mean_cm median_cm std_cm\n  <chr>                  <int>   <dbl>     <dbl>  <dbl>\n1 Acanthurus chronixis      21    13.7      12.5  2.65 \n2 Anampses spp.             17    17.5      16.5  4.43 \n3 Calotomus carolinus      176    16.4      16.5  3.05 \n4 Cheilinus chlorourus       4    13.9      14    0.810\n5 Leptoscarus vaigiensis   146    18.1      17.5  3.53 \n6 Lethrinus harak           37    12.6      12    2.72 \n7 Lethrinus mahsena        135    11.9      11.9  2.39 \n8 Lutjanus fulviflamma      47    16.7      16.9  2.67 \n9 Siganus sutor            196    18.2      17.5  4.66 \n```\n\n\n:::\n:::\n\n\nIn some cases, you might wish to arrange the sample size from lowest to highest sample size along with the computed values. You just add the `arrange` function\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlfq.sample1 %>% \n  group_by(species) %>% \n  summarise(\n    n = n(),\n    mean_cm = mean(size_cm),\n    median_cm = median(size_cm),\n    std_cm = sd(size_cm)\n    ) %>% \n  arrange(n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 5\n  species                    n mean_cm median_cm std_cm\n  <chr>                  <int>   <dbl>     <dbl>  <dbl>\n1 Cheilinus chlorourus       4    13.9      14    0.810\n2 Anampses spp.             17    17.5      16.5  4.43 \n3 Acanthurus chronixis      21    13.7      12.5  2.65 \n4 Lethrinus harak           37    12.6      12    2.72 \n5 Lutjanus fulviflamma      47    16.7      16.9  2.67 \n6 Lethrinus mahsena        135    11.9      11.9  2.39 \n7 Leptoscarus vaigiensis   146    18.1      17.5  3.53 \n8 Calotomus carolinus      176    16.4      16.5  3.05 \n9 Siganus sutor            196    18.2      17.5  4.66 \n```\n\n\n:::\n:::\n\n\nYou notice that *Cheilinus chlorourus* has a only four observation where as *Siganus sutor* has 196 records in the dataset. You can also explore the summary statistics to see whether the mean and median values are close (indicator of normal distribution) or differ (indication of skewness)\n\n\n## References\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}